use crate::analysis::{invariant_languages, machinery_permissions, property_records};
use crate::fixtures::corpus;
use crate::{AUTHORITY, G3_ROOT, G4_ROOT, G5_ROOT, G6_ROOT, RESULT};
use serde_json::{Value, json};

pub fn contracts() -> Vec<(&'static str, Value)> {
    let properties = property_records();
    let permissions = machinery_permissions();
    vec![
        (
            "FORMAL_ANALYSIS_BOUNDARY_V1.json",
            json!({
                "schema":"G7_FORMAL_ANALYSIS_BOUNDARY_V1",
                "question":"WHICH_VERDICTS_CAN_MATHEMATICS_LEGITIMATELY_AUTHORIZE",
                "metatheory_separate_from_certification":true,
                "property_count":properties.len(),
                "result":RESULT,
                "authority":AUTHORITY,
                "production_judge_authorized":false
            }),
        ),
        (
            "DECISION_PROBLEM_INSTANCE_UNIVERSE_V1.json",
            json!({
                "schema":"G7_DECISION_PROBLEM_INSTANCE_UNIVERSE_V1",
                "primitive_objects":["G3_CONTEXT_INDEXED_CONFIGURATIONS_TRANSITIONS_PREFIXES","G4_23_COMPONENT_SURFACE","G5_TRUE_FINITE_CONTINUATIONS_WITH_SOUND_ENVELOPE","G6_SAME_FIBER_PREFIX_PAIRS"],
                "qualified_inputs":["CONSTRUCTIVE_ANCESTRY_HISTORY","SYMBOLIC_CONFIGURATION_WITH_TYPED_CONTEXT","SAME_FIBER_PAIR","REGISTERED_INVARIANT_FORMULA","FINITE_RELATIVE_TOKEN_WORD"],
                "excluded":["REAL_PAIR_MINING","OUTCOME_BEARING_INPUT","OMEGA_TRACE","UNQUALIFIED_CONTEXT","CROSS_FIBER_NON_EQUIVALENCE"]
            }),
        ),
        ("PROPERTY_DECIDABILITY_MATRIX_V1.json", json!(properties)),
        (
            "SEMANTIC_PROPERTY_TABLE_V1.json",
            json!([
                {"property":"REACHABILITY","truth_target":"TRUE_G3_CONTEXT_INDEXED_REACHABILITY","definition_exact":true,"decision_status":"UNKNOWN"},
                {"property":"INVARIANT_PRESERVATION","truth_target":"LANGUAGE_PARAMETERIZED_SEMANTIC_INVARIANCE_OR_INDUCTIVENESS","definition_exact":true,"decision_status":"RESTRICTED"},
                {"property":"BEHAVIORAL_EQUIVALENCE","truth_target":"G6_EXACT_FINITE_TRACE_RELATION","definition_exact":true,"decision_status":"UNKNOWN"},
                {"property":"BEHAVIORAL_NON_EQUIVALENCE","truth_target":"NEGATION_INSIDE_G6_FIBER","definition_exact":true,"decision_status":"RECOGNIZABLE"},
                {"property":"DISTINGUISHING_WITNESS_EXISTENCE","truth_target":"FINITE_G4_MISMATCH_UNDER_LAWFUL_G5_CONTINUATION","definition_exact":true,"decision_status":"RECOGNIZABLE"},
                {"property":"DISTINGUISHING_WITNESS_MINIMALITY","truth_target":"NO_STRICTLY_CHEAPER_LAWFUL_SEPARATOR","definition_exact":true,"decision_status":"UNKNOWN"}
            ]),
        ),
        (
            "INSTANCE_CERTIFICATION_TABLE_V1.json",
            json!([
                {"signature":"G7_REACH_SYMBOLIC_CONFIGURATION_V1","positive":"VERIFIED_ANCESTRY","negative":"PROVED_G3_EXCLUSION_ONLY","unknown":"SEARCH_FAILURE"},
                {"signature":"G7_INVARIANT_LANGUAGE_PARAMETERIZED_V1","positive":"NAMED_SCOPE_INDUCTIVENESS_PROOF","negative":"CONCRETE_NONINDUCTIVE_TRANSITION","unknown":"SEMANTIC_INVARIANCE_WITHOUT_REACHABILITY"},
                {"signature":"G7_G6_FIBER_EQUIVALENCE_V1","positive":"SCOPE_COMPLETE_UNIVERSAL_PROOF","negative":"VERIFIED_SEPARATOR","unknown":"BOUNDED_UNSAT_OR_NO_WITNESS"},
                {"signature":"G7_G6_FIBER_NON_EQUIVALENCE_V1","positive":"VERIFIED_SEPARATOR","negative":"NO_AUTHORITY_FROM_SEARCH_FAILURE"},
                {"signature":"G7_FINITE_SEPARATOR_EXISTENCE_V1","positive":"VERIFIED_SEPARATOR","negative":"NO_AUTHORITY_FROM_SEARCH_FAILURE"},
                {"signature":"G7_GLOBAL_SEPARATOR_MINIMALITY_V1","positive":"BOUNDED_FINITE_BOX_ONLY","negative":"VERIFIED_CHEAPER_SEPARATOR","global":"UNKNOWN"}
            ]),
        ),
        (
            "EFFECTIVE_PRESENTATION_REGISTRY_V1.json",
            json!([
                {"object":"G1_STEP","status":"EFFECTIVE_TOTAL_ON_G1_DOMAIN","termination":"EARNED"},
                {"object":"G3_TRUE_REACHABLE_SET","status":"NOT_EXACTLY_EFFECTIVELY_PRESENTED","bounds":"K_MINUS_SUBSET_K_REACH_SUBSET_K_PLUS"},
                {"object":"G5_RELATIVE_TOKEN_ALPHABET","status":"EFFECTIVELY_ENUMERABLE","encoding":"CANONICAL_SIGNED_INTEGER_TUPLES"},
                {"object":"G5_FINITE_TOKEN_WORDS","status":"EFFECTIVELY_ENUMERABLE","enumeration":"LENGTH_THEN_INTEGER_HEIGHT_THEN_LEXICOGRAPHIC"},
                {"object":"G5_TRUE_PRESENTABILITY_PER_WORD","status":"DECIDABLE_BY_TERMINATING_REALIZATION","upper_envelope_alone":"INSUFFICIENT"},
                {"object":"G4_MISMATCH","status":"DECIDABLE_FOR_CONCRETE_FINITE_TRACE","blind_spot":"GRAMMAR_STATE_AND_EVENT_NOT_EVALUABLE"}
            ]),
        ),
        (
            "ANALYSIS_ROUTE_REGISTRY_V1.json",
            json!([
                {"route_id":"G7_REACHABILITY_COMPOSITIONAL_V1","components":["ANCESTRY_VERIFIER","BOUNDED_KERNEL_UNROLLING","G3_TRANSFER_RULES"],"complete":false},
                {"route_id":"G7_INVARIANT_LANGUAGE_SPLIT_V1","components":["FINITE_CASES","INTEGER_LINEAR_ARITHMETIC","STRUCTURAL_PROOF","TRACE_MONITOR_WHEN_QUALIFIED"],"complete":false},
                {"route_id":"G7_EQUIVALENCE_COMPOSITIONAL_PROOF_V1","components":["G6_FIBER_CHECK","G5_LANGUAGE","G4_MATCH","CORRESPONDENCE_EVOLUTION"],"complete":false},
                {"route_id":"G7_FINITE_SEPARATOR_ENUMERATION_V1","components":["FAIR_TOKEN_ENUMERATOR","REALIZER","KERNEL_FOLD","EXACT_MISMATCH_VERIFIER"],"complete_on_positive_instances":true},
                {"route_id":"G7_MINIMALITY_LOWER_CONE_V1","components":["COST_ORDER","LOWER_CONE_ENUMERATION","WITNESS_VERIFIER"],"global_complete":false}
            ]),
        ),
        (
            "ANALYSIS_ROUTE_COMPOSITION_PROOFS_V1.json",
            json!([
                {"route":"FINITE_SEPARATOR","seam":"TOKEN_ENUMERATOR_TO_REALIZER","preserves":"EVERY_FINITE_CANONICAL_TOKEN_WORD_EVENTUALLY_ENUMERATED","status":"PROVEN_BY_DOVETAIL_ENUMERATION"},
                {"route":"FINITE_SEPARATOR","seam":"REALIZER_TO_KERNEL","preserves":"TRUE_PRESENTABILITY_AND_ORDERED_EXECUTION","status":"INHERITED_G5_G1"},
                {"route":"FINITE_SEPARATOR","seam":"KERNEL_TO_G4_MATCH","preserves":"EXACT_PROTECTED_MISMATCH","status":"INHERITED_G6"},
                {"route":"UNIVERSAL_UPPER_ENVELOPE","seam":"SUPERSET_TO_TRUE_DOMAIN","preserves":"UNIVERSAL_PROPERTY_DOWNWARD","status":"PROVEN_SET_INCLUSION"},
                {"route":"BOUNDED_COUNTEREXAMPLE","seam":"UPPER_ENVELOPE_TO_TRUE_DOMAIN","preserves":"NOT_AUTOMATIC","status":"CONSTRUCTIVE_VALIDATION_REQUIRED"}
            ]),
        ),
        (
            "FORMALISM_FIT_MATRIX_V1.json",
            json!([
                {"formalism":"FINITE_STATE","fit":"PARTIAL_CONTROL_ONLY","whole_observer":false},
                {"formalism":"PRESBURGER_INTEGER_TRANSITION_SYSTEM","fit":"OPERATION_LEVEL_PARTIAL","whole_observer":false},
                {"formalism":"RA_Q","fit":"RESEMBLANCE_WITH_FAILED_THEOREM_TRANSFER","whole_observer":false},
                {"formalism":"EVENT_SOURCED_TRANSDUCER","fit":"SEMANTIC_DESCRIPTION_NOT_DECIDABILITY_THEOREM","whole_observer":false},
                {"formalism":"COMPOSITIONAL_MIXED_SYSTEM","fit":"PRIMARY_ANALYSIS_POSTURE","whole_observer":true,"complete_decision_theory":false}
            ]),
        ),
        (
            "THEOREM_PRECONDITION_REGISTRY_V1.json",
            json!([
                {"theorem":"DETERMINISTIC_COPYLESS_RA_Q_EQUIVALENCE_PSPACE","source":"https://lcs.ios.ac.cn/~wuzl/pub/cltw-lics2017.pdf","preconditions":["DETERMINISTIC_RA_Q","COPYLESS","MATCHING_EQUIVALENCE_SIGNATURE","EFFECTIVE_SEMANTICS_PRESERVING_REDUCTION"],"northstar_status":"NOT_ALL_EARNED"},
                {"theorem":"COPYLESS_NONSTRICT_RA_Q_REACHABILITY_NEXPTIME","source":"https://lcs.ios.ac.cn/~wuzl/pub/cltw-lics2017.pdf","preconditions":["COPYLESS_RA_Q","NONSTRICT_GUARDS","MATCHING_REACHABILITY_SIGNATURE","EFFECTIVE_SEMANTICS_PRESERVING_REDUCTION"],"northstar_status":"FAILED_STRICT_GUARD_AND_REDUCTION_BOUNDARY"},
                {"theorem":"GENERAL_DETERMINISTIC_RA_Q_REACHABILITY_UNDECIDABLE","source":"https://lcs.ios.ac.cn/~wuzl/pub/cltw-lics2017.pdf","preconditions":["REDUCTION_FROM_UNDECIDABLE_SOURCE_TO_EXACT_NORTHSTAR_PROBLEM"],"northstar_status":"NO_UNDECIDABILITY_TRANSFER"}
            ]),
        ),
        (
            "THEOREM_TRANSFER_REDUCTION_REGISTRY_V1.json",
            json!([
                {"transfer_id":"RAQ_EQUIVALENCE_TO_G6","direction":"NORTHSTAR_TO_RA_Q_FOR_POSITIVE_DECIDABILITY","effective":false,"property_preservation":"NOT_EARNED","property_reflection":"NOT_EARNED","result":"NO_BRIDGE_EARNED"},
                {"transfer_id":"RAQ_REACHABILITY_TO_G3","direction":"NORTHSTAR_TO_RA_Q_FOR_POSITIVE_DECIDABILITY","effective":false,"property_preservation":"NOT_EARNED","property_reflection":"NOT_EARNED","result":"NO_BRIDGE_EARNED"},
                {"transfer_id":"RAQ_UNDECIDABILITY_TO_NORTHSTAR","direction":"UNDECIDABLE_SOURCE_TO_NORTHSTAR","effective":false,"property_preservation":"NOT_EARNED","property_reflection":"NOT_EARNED","result":"NO_BRIDGE_EARNED"}
            ]),
        ),
        (
            "NORTHSTAR_FORMALISM_MEMBERSHIP_REGISTRY_V1.json",
            json!({
                "whole_kernel":{"formalism":"RA_Q","membership":"NOT_EARNED","reasons":["STRICT_RENEWAL_GUARDS","GENEALOGY_AND_ORDERED_EMISSIONS","APPLIED_REJECTED_SEMANTICS","FULL_COPYLESS_PARTITION_NOT_PROVEN","G6_FIBER_CORRESPONDENCE_NOT_RA_Q_EQUIVALENCE_BY_DEFAULT"]},
                "subsystems":[{"id":"AFFINE_REGISTER_UPDATES","membership":"OPERATION_LEVEL_RESEMBLANCE_ONLY"},{"id":"FINITE_CONTROL","membership":"RESTRICTED_EXACT"}],
                "fixtures_can_establish_membership":false
            }),
        ),
        (
            "EVIDENCE_CLASS_REGISTRY_V1.json",
            json!([
                {"class":"SEALED_SEMANTIC_AUTHORITY","may_earn":"NORTHSTAR_SEMANTIC_TARGET"},
                {"class":"LITERATURE_THEOREM","may_earn":"THEOREM_STATEMENT_ONLY","cannot_earn":"NORTHSTAR_MEMBERSHIP"},
                {"class":"TYPED_REDUCTION_PROOF","may_earn":"THEOREM_TRANSFER"},
                {"class":"EXECUTABLE_CERTIFICATE","may_earn":"INSTANCE_RESULT_WITHIN_SCHEMA"},
                {"class":"SYNTHETIC_VALIDATION_ONLY","may_earn":"IMPLEMENTATION_SEMANTICS","cannot_earn":"METATHEOREM_OR_REAL_INSTANCE"}
            ]),
        ),
        (
            "INVARIANT_LANGUAGE_REGISTRY_V1.json",
            json!(invariant_languages()),
        ),
        (
            "SEMANTIC_PROPERTY_RELATION_REGISTRY_V1.json",
            json!([
                {"left":"G6_BEHAVIORAL_NON_EQUIVALENCE","right":"FINITE_PROTECTED_SEPARATOR_EXISTS","relation":"IFF","scope":"SAME_LAWFUL_G6_FIBER"},
                {"left":"NON_COMPARABLE","right":"BEHAVIORALLY_NON_EQUIVALENT","relation":"DISTINCT","scope":"ALL"},
                {"left":"INDUCTIVE","right":"SEMANTICALLY_INVARIANT","relation":"IMPLIES_IF_INIT_INCLUDED_AND_TRANSITION_SCOPE_SOUND","converse":false},
                {"left":"VERIFIED_SEPARATOR","right":"MINIMAL_SEPARATOR","relation":"DOES_NOT_IMPLY"}
            ]),
        ),
        (
            "EFFECTIVE_WITNESS_SEARCH_ANALYSIS_V1.json",
            json!({
                "promise_domain":"CONSTRUCTIVE_SAME_FIBER_STARTS",
                "alphabet":"COUNTABLE_CANONICAL_INTEGER_RELATIVE_TOKENS",
                "word_enumeration":"FAIR_DOVETAIL_BY_LENGTH_AND_INTEGER_HEIGHT",
                "candidate_realization":"TERMINATING",
                "kernel_execution":"TERMINATING_PER_FINITE_WORD",
                "mismatch_verification":"DECIDABLE",
                "metatheoretic_status":"RECOGNIZABLE",
                "no_witness_termination":"NOT_GUARANTEED"
            }),
        ),
        (
            "WITNESS_COST_CONTRACT_V1.json",
            json!({
                "order":"LEXICOGRAPHIC",
                "coordinates":["EXPERIMENT_TOKEN_COUNT","TOTAL_PRESENTATIONS_LEFT_PLUS_RIGHT","APPLIED_CAUSAL_PROGRESS_LEFT_PLUS_RIGHT","CANONICAL_TOKEN_ENCODING"],
                "experiment_token_and_causal_progress_distinct":true,
                "rejected_step":{"experiment_tokens":1,"causal_progress":0},
                "well_founded":true,
                "token_length_bounds_integer_magnitude":false
            }),
        ),
        (
            "WITNESS_MINIMALITY_ANALYSIS_V1.json",
            json!({
                "global_status":"UNKNOWN",
                "reason":"STRICT_LOWER_COST_CONE_MAY_CONTAIN_INFINITELY_MANY_INTEGER_VALUED_TOKENS_AND_NO_COMPLETE_NO_WITNESS_DECIDER_IS_EARNED",
                "restricted_status":"EXACT_WITHIN_EXPLICIT_FINITE_TOKEN_BOX",
                "required_receipt":["BOX_BOUNDS","COST_ORDER","COMPLETE_LOWER_CONE_ENUMERATION","VERIFIER_VERSION","NO_CHEAPER_ACCEPTED_CERTIFICATE"],
                "first_found_is_minimal":false
            }),
        ),
        (
            "CERTIFICATE_SCHEMA_REGISTRY_V1.json",
            json!([
                {"schema":"QUALIFIED_ANCESTRY_CERTIFICATE_V1","required":["context","initialization","ordered_inputs","ordered_states","ordered_emissions","G1_fold_hash","G3_scope"]},
                {"schema":"FINITE_SEPARATOR_CERTIFICATE_V1","required":["left_ancestry","right_ancestry","fiber","Lambda_realization","finite_tokens","presentability","correspondence_trace","first_G4_mismatch"]},
                {"schema":"RESTRICTED_INDUCTIVENESS_CERTIFICATE_V1","required":["language","formula","init_proof","transition_partition","consecution_proof","scope"]},
                {"schema":"BOUNDED_MINIMALITY_CERTIFICATE_V1","required":["separator","finite_box","cost","lower_cone_manifest","verifier_receipt"]}
            ]),
        ),
        (
            "CERTIFICATE_VERIFIER_AUTHORITY_V1.json",
            json!({
                "architecture":"EXPLORER_TO_CERTIFICATE_TO_SMALL_EXACT_VERIFIER",
                "authorized_verifiers":["QUALIFIED_ANCESTRY","FINITE_SEPARATOR","RESTRICTED_INDUCTIVENESS","FINITE_BOX_MINIMALITY"],
                "explorer_has_verdict_authority":false,
                "accepted_certificate_scope_cannot_be_widened":true
            }),
        ),
        (
            "SEARCH_VS_VERIFICATION_AUTHORITY_V1.json",
            json!({
                "search_may_be":["INCOMPLETE","HEURISTIC","BOUNDED","SOLVER_ASSISTED","ENUMERATIVE"],
                "search_output":"CANDIDATE_ONLY",
                "verification_output":"AUTHORITATIVE_ONLY_IF_SCHEMA_AND_SCOPE_PASS",
                "failure_to_find":"UNKNOWN",
                "bounded_unsat":"NO_GLOBAL_EQUIVALENCE_AUTHORITY"
            }),
        ),
        (
            "DECIDABILITY_FAILURE_BOUNDARY_V1.json",
            json!([
                {"boundary":"NO_EXACT_TRUE_G3_REACHABLE_SET_PRESENTATION","blocks":["GLOBAL_REACHABILITY_DECIDER","SEMANTIC_INVARIANCE_TRANSFER"]},
                {"boundary":"NO_COMPLETE_TRUE_G5_CONTINUATION_LANGUAGE_CHARACTERIZATION","blocks":["GENERIC_EQUIVALENCE_DECIDER_TRANSFER"]},
                {"boundary":"NO_WHOLE_KERNEL_RA_Q_MEMBERSHIP_OR_REDUCTION","blocks":["RA_Q_EQUIVALENCE_AND_REACHABILITY_THEOREM_TRANSFER"]},
                {"boundary":"INFINITE_GLOBAL_LOWER_COST_CONES","blocks":["GLOBAL_WITNESS_MINIMALITY_CERTIFICATION"]},
                {"boundary":"G4_GRAMMAR_BLIND_SPOT","blocks":["GRAMMAR_BEHAVIOR_EQUIVALENCE_CLAIMS"]}
            ]),
        ),
        (
            "RA_Q_THEOREM_TRANSFER_PROBE_V1.json",
            json!({
                "source":"https://lcs.ios.ac.cn/~wuzl/pub/cltw-lics2017.pdf",
                "observer_operations":{"strict_upper_renewal":"high > upper","strict_lower_renewal":"low < lower","copyless_whole_kernel":"NOT_PROVEN","guard_data_partition":"NOT_PROVEN_FOR_WHOLE_KERNEL","ordered_emissions_and_genealogy":"OUTSIDE_UNESTABLISHED_ENCODING"},
                "equivalence_theorem":{"literature_result":"DETERMINISTIC_COPYLESS_RA_Q_PSPACE_COMPLETE","northstar_transfer":"NOT_EARNED"},
                "reachability_theorem":{"literature_result":"COPYLESS_NONSTRICT_RA_Q_IN_NEXPTIME","non_strict_definition":"POSITIVE_BOOLEAN_COMBINATIONS_OF_NONSTRICT_ORDER","northstar_transfer":"FAILED_STRICT_GUARD_BOUNDARY_AND_NO_REDUCTION"},
                "general_undecidability":{"literature_result":"DETERMINISTIC_RA_Q_REACHABILITY_UNDECIDABLE","northstar_transfer":"NOT_EARNED_WITHOUT_REDUCTION_INTO_NORTHSTAR"},
                "result":"NO_WHOLE_OBSERVER_THEOREM_BRIDGE_EARNED"
            }),
        ),
        (
            "APPROXIMATION_TRANSFER_RULE_REGISTRY_V1.json",
            json!([
                {"rule_id":"G3_UNDERAPPROX_POSITIVE","premise":"x IN TRUE_CONSTRUCTIVE_UNDERAPPROX","conclusion":"x IN TRUE_REACHABLE","direction":"SOUND_POSITIVE"},
                {"rule_id":"G3_OVERAPPROX_UNIVERSAL","premise":"FOR_ALL x IN SOUND_OVERAPPROX P(x)","conclusion":"FOR_ALL x IN TRUE_REACHABLE P(x)","direction":"SOUND_UNIVERSAL_DOWNWARD"},
                {"rule_id":"G3_OVERAPPROX_COUNTEREXAMPLE","premise":"EXISTS x IN SOUND_OVERAPPROX NOT_P(x)","conclusion":"CANDIDATE_ONLY_UNTIL_CONSTRUCTIVE","direction":"NO_NEGATIVE_TRANSFER"},
                {"rule_id":"G5_TRUE_PRESENTABILITY_REQUIRED","premise":"TOKEN_WORD_REALIZES_IN_TRUE_LANGUAGE","conclusion":"MAY_CERTIFY_SEPARATOR","direction":"SOUND_POSITIVE"},
                {"rule_id":"G5_UPPER_ENVELOPE_CANDIDATE_NOT_CERTIFICATE","premise":"TOKEN_WORD_ONLY_IN_U_PLUS","conclusion":"CANDIDATE_NOT_CERTIFICATE","direction":"NO_TRANSFER"}
            ]),
        ),
        (
            "SOUNDNESS_COMPLETENESS_REGISTRY_V1.json",
            json!(
                properties
                    .iter()
                    .map(|row| json!({
                        "problem_signature_id":row.problem_signature_id,
                        "soundness":row.soundness,
                        "completeness":row.completeness,
                        "termination":row.termination
                    }))
                    .collect::<Vec<_>>()
            ),
        ),
        ("MACHINERY_PERMISSION_REGISTRY_V1.json", json!(permissions)),
        (
            "G3_G5_RESTRICTION_INHERITANCE_V1.json",
            json!({
                "G3_root":G3_ROOT,"G5_root":G5_ROOT,
                "inherited":["CONSTRUCTIVE_UNDERAPPROX","SOUND_OVERAPPROX","UNKNOWN_TRUE_REACHABILITY","PARAMETRIC_SOUND_CONTINUATION_ENVELOPE","TRUE_PRESENTABILITY_REQUIRED"],
                "restrictions_weakened":false
            }),
        ),
        (
            "G4_BLIND_SPOT_INHERITANCE_V1.json",
            json!({
                "G4_root":G4_ROOT,"GrammarStateAndEvent":"NOT_EVALUABLE","propagation":"UNCHANGED","formal_analysis_cannot_manufacture_missing_AUTHORITY":true
            }),
        ),
        (
            "G6_SEMANTIC_TARGET_INHERITANCE_V1.json",
            json!({
                "G6_root":G6_ROOT,"relation":"EXACT_FINITE_TRACE_FIBERWISE_BEHAVIORAL_EQUIVALENCE","mutated":false,"omega_trace":"NOT_EARNED","liveness":"NOT_EARNED"
            }),
        ),
        ("FORMALISM_VALIDATION_FIXTURES_V1.json", json!(corpus())),
    ]
}
