use crate::contracts::{GateStatus, IndexKey};
use crate::office::{LifecycleLedgerSnapshot, LifecycleReceipt, ReceiptKind};
use std::sync::Arc;

pub(super) fn fixture() -> LifecycleLedgerSnapshot {
    let receipts: Arc<[LifecycleReceipt]> = vec![
        receipt(
            1_851,
            Some(1_850),
            "09:41:06.118",
            Some(IndexKey::Us100),
            ReceiptKind::Position,
            "TradeLocker",
            "Position 9401 confirmed / long 0.10",
            "opened by order 77182 / average 20,097.2",
            Some(0.31),
            "positionId 9401",
            1_420,
            GateStatus::Pass,
            "tl-position-9401",
        ),
        receipt(
            1_850,
            Some(1_849),
            "09:41:06.101",
            Some(IndexKey::Us100),
            ReceiptKind::Fill,
            "TradeLocker",
            "Fill 88014 applied exactly once",
            "0.10 @ 20,097.2 / slippage 0.4pt",
            Some(0.31),
            "fillId 88014 / orderId 77182",
            1_403,
            GateStatus::Pass,
            "tl-fill-88014",
        ),
        receipt(
            1_849,
            Some(1_848),
            "09:41:05.692",
            Some(IndexKey::Us100),
            ReceiptKind::VenueOrder,
            "TradeLocker",
            "Order 77182 accepted",
            "limit 20,097.6 / strategy MOM-US100-L",
            Some(0.31),
            "orderId 77182",
            994,
            GateStatus::Pass,
            "tl-order-77182",
        ),
        receipt(
            1_848,
            Some(1_847),
            "09:41:05.244",
            Some(IndexKey::Us100),
            ReceiptKind::CommandIntent,
            "Northstar",
            "Submit intent authorized",
            "quantity 0.10 / stop 20,072 / target 20,180",
            Some(0.31),
            "intentId 41",
            546,
            GateStatus::Pass,
            "intent-41",
        ),
        receipt(
            1_847,
            Some(1_846),
            "09:41:05.109",
            Some(IndexKey::Us100),
            ReceiptKind::RiskEvaluation,
            "Nautilus risk",
            "Portfolio and daily limits passed",
            "heat 0.63R / daily 0.74R / event lock clear",
            Some(0.31),
            "no venue command yet",
            411,
            GateStatus::Pass,
            "risk-snapshot-443",
        ),
        receipt(
            1_846,
            Some(1_845),
            "09:41:05.018",
            Some(IndexKey::Us100),
            ReceiptKind::Decision,
            "Momentum-5m r8f13a2",
            "Held LONG after spread gate passed",
            "market 118839 / macro 1188402 / fund 443",
            Some(0.31),
            "route eligible",
            320,
            GateStatus::Pass,
            "decision-e1a4",
        ),
        receipt(
            1_845,
            None,
            "09:41:04.892",
            Some(IndexKey::Us100),
            ReceiptKind::Observation,
            "Massive",
            "US100 bar and quote snapshot published",
            "reference 20,096.8 / basis 0.8 / spread 1.6",
            None,
            "reference only",
            194,
            GateStatus::Pass,
            "market-snapshot-118839",
        ),
        receipt(
            1_844,
            None,
            "09:36:11.004",
            Some(IndexKey::Us30),
            ReceiptKind::Decision,
            "Mean-revert r22b10c",
            "Entry suppressed by operating conflict",
            "expansion state conflicts with mean-revert policy",
            Some(0.0),
            "no order",
            281,
            GateStatus::Block,
            "decision-cc72",
        ),
        receipt(
            1_843,
            None,
            "09:35:12.200",
            Some(IndexKey::Jp225),
            ReceiptKind::Incident,
            "e-Stat calendar",
            "Industrial production release late",
            "scheduled 09:28 / no publication receipt",
            None,
            "not applicable",
            0,
            GateStatus::Observe,
            "incident-5301",
        ),
        receipt(
            1_842,
            None,
            "09:31:42.011",
            Some(IndexKey::Us500),
            ReceiptKind::Decision,
            "Open-range r310a7f",
            "Breakout candidate retained in shadow",
            "breadth 0.74 / liquidity healthy / no route",
            Some(0.18),
            "shadow only",
            305,
            GateStatus::Observe,
            "decision-b720",
        ),
        receipt(
            1_841,
            None,
            "08:42:01.003",
            None,
            ReceiptKind::Observation,
            "Macro publisher",
            "US CPI vintage 114 published",
            "actual 2.9 / previous 2.7 / receipt bls-91f2",
            None,
            "not applicable",
            1_880,
            GateStatus::Pass,
            "macro-snapshot-1188402",
        ),
        receipt(
            1_840,
            None,
            "08:29:58.411",
            None,
            ReceiptKind::Reconciliation,
            "TradeLocker/Nautilus",
            "Execution epoch 9 completed",
            "orders 2 / positions 1 / unknown 0",
            None,
            "SyncEnd received",
            18_400,
            GateStatus::Pass,
            "reconcile-epoch-9",
        ),
    ]
    .into();
    LifecycleLedgerSnapshot {
        receipts,
        decisions: 3,
        routed: 1,
        blocked: 1,
        fills: 1,
        unknown: 0,
        incidents: 1,
    }
}

#[allow(clippy::too_many_arguments)]
fn receipt(
    receipt_id: u64,
    parent_id: Option<u64>,
    time_label: &'static str,
    index: Option<IndexKey>,
    kind: ReceiptKind,
    origin: &'static str,
    summary: &'static str,
    evidence: &'static str,
    risk_r: Option<f32>,
    venue_truth: &'static str,
    latency_us: u32,
    status: GateStatus,
    provenance: &'static str,
) -> LifecycleReceipt {
    LifecycleReceipt {
        receipt_id,
        parent_id,
        time_label,
        index,
        kind,
        origin,
        summary,
        evidence,
        risk_r,
        venue_truth,
        latency_us,
        status,
        provenance,
    }
}
