use super::*;

pub(in crate::operating) enum MacroRuntimeCommand {
    Bls(MacroRefresh<Vec<FetchedMacroReceipt>>),
    BlsCalendar(MacroRefresh<FetchedBlsCalendarReceipt>),
    Cftc(MacroRefresh<FetchedCftcReceipt>),
    Eurostat(MacroRefresh<Vec<FetchedEurostatReceipt>>),
    Fred(MacroRefresh<Vec<FetchedFredReceipt>>),
    Bea(MacroRefresh<Vec<FetchedBeaReceipt>>),
    Census(MacroRefresh<FetchedCensusReceipt>),
    Ecb(MacroRefresh<Vec<FetchedEcbReceipt>>),
    Ons(MacroRefresh<Vec<FetchedOnsReceipt>>),
    Boe(MacroRefresh<Vec<FetchedBoeReceipt>>),
    Boj(MacroRefresh<Vec<FetchedBojReceipt>>),
    Failure(SourceId, crate::data_plane::ids::StreamId, Arc<str>, i64),
}

pub(super) fn handle_macro_command(
    command: MacroRuntimeCommand,
    macro_plane: &mut MacroPlane,
    store: &mut LedgerStore,
    projector: &mut LedgerProjector,
    publisher: &mut SnapshotPublisher,
) {
    match command {
        MacroRuntimeCommand::Bls(refresh) => finish(
            macro_plane.ingest_complete_bls_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "BLS",
            BLS_SOURCE,
            BLS_TIMESERIES_STREAM,
            BLS_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::BlsCalendar(refresh) => finish(
            macro_plane.ingest_bls_calendar_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "BLS calendar",
            BLS_SOURCE,
            BLS_RELEASE_CALENDAR_STREAM,
            BLS_CALENDAR_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Cftc(refresh) => finish(
            macro_plane.ingest_complete_cftc_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "CFTC TFF",
            CFTC_SOURCE,
            CFTC_TFF_STREAM,
            CFTC_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Eurostat(refresh) => finish(
            macro_plane.ingest_complete_eurostat_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "Eurostat",
            EUROSTAT_SOURCE,
            EUROSTAT_STATISTICS_STREAM,
            EUROSTAT_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Fred(refresh) => finish(
            macro_plane.ingest_complete_fred_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "FRED",
            FRED_SOURCE,
            FRED_OBSERVATIONS_STREAM,
            FRED_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Bea(refresh) => finish(
            macro_plane.ingest_complete_bea_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "BEA",
            BEA_SOURCE,
            BEA_NIPA_STREAM,
            BEA_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Census(refresh) => finish(
            macro_plane.ingest_census_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "Census",
            CENSUS_SOURCE,
            CENSUS_MARTS_STREAM,
            CENSUS_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Ecb(refresh) => finish(
            macro_plane.ingest_complete_ecb_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "ECB",
            ECB_SOURCE,
            ECB_POLICY_RATES_STREAM,
            ECB_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Ons(refresh) => finish(
            macro_plane.ingest_complete_ons_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "ONS",
            ONS_SOURCE,
            ONS_TIMESERIES_STREAM,
            ONS_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Boe(refresh) => finish(
            macro_plane.ingest_complete_boe_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "Bank of England",
            BOE_SOURCE,
            BOE_RATES_STREAM,
            BOE_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Boj(refresh) => finish(
            macro_plane.ingest_complete_boj_refresh(refresh.payload, refresh.next_refresh_ns),
            refresh.acknowledgement,
            "Bank of Japan",
            BOJ_SOURCE,
            BOJ_TIMESERIES_STREAM,
            BOJ_FAILURE_RETRY,
            macro_plane,
            store,
            projector,
            publisher,
        ),
        MacroRuntimeCommand::Failure(source, stream, message, next_refresh_ns) => {
            publisher.publish_macro(macro_plane.failure_snapshot(
                source,
                stream,
                message,
                next_refresh_ns,
            ));
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn finish(
    result: Result<MacroIngestReport, MacroPlaneError>,
    acknowledgement: Sender<bool>,
    label: &'static str,
    source: SourceId,
    stream: crate::data_plane::ids::StreamId,
    retry: Duration,
    macro_plane: &mut MacroPlane,
    store: &mut LedgerStore,
    projector: &mut LedgerProjector,
    publisher: &mut SnapshotPublisher,
) {
    let accepted = publish_macro_result(
        result,
        label,
        source,
        stream,
        retry,
        macro_plane,
        store,
        projector,
        publisher,
    );
    let _ = acknowledgement.send(accepted);
}
