use crate::emissions::emission_elements;
use crate::model::{CarryStatus, ElementRole, Role, Surface};

pub(crate) fn element_census() -> Vec<ElementRole> {
    use CarryStatus as C;
    use Role as R;
    use Surface as S;
    let mut out = vec![
        e(
            "state.initialized",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::ControlStateQ,
                R::GuardRegister,
                R::UsedInGuard,
                R::ConstantUpdate,
                R::AuthoritativeStateOutput,
            ],
            &["init", "prior state domain"],
            "false at init; true after every admitted step; prior value participates in domain validation",
            true,
            false,
            "KernelState.initialized",
        ),
        e(
            "state.bar_index",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::ArithmeticRegister,
                R::ReadFromPriorState,
                R::AffineUpdate,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            &["prior bar_index", "first-step zero"],
            "zero on first step, otherwise prior + 1",
            true,
            false,
            "CommittedState.bar_index",
        ),
        e(
            "state.knowledge_time_ns",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::GuardRegister,
                R::UsedInGuard,
                R::CopiedFromInput,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            &["input.knowledge_time_ns"],
            "copies current completed-bar knowledge time; prior value guards chronology",
            true,
            true,
            "CommittedState.knowledge_time",
        ),
        candidate(
            "state.upper.id",
            "upper",
            "id",
            &[
                R::ArithmeticRegister,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::DerivedEmission,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; prior + 1 on strict renewal",
            true,
            true,
        ),
        candidate(
            "state.upper.value_ticks",
            "upper",
            "value",
            &[
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::CopiedFromInput,
                R::CopiedFromPriorState,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            "copy prior on hold; copy input high on strict renewal",
            true,
            false,
        ),
        candidate(
            "state.upper.birth_bar_index",
            "upper",
            "birth_bar",
            &[
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; reset to current bar index on renewal",
            true,
            false,
        ),
        candidate(
            "state.upper.birth_knowledge_time_ns",
            "upper",
            "birth_knowledge_time",
            &[
                R::CopiedFromInput,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; reset to current knowledge time on renewal",
            true,
            false,
        ),
        candidate(
            "state.upper.age_bars",
            "upper",
            "age",
            &[
                R::ArithmeticRegister,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "prior + 1 on hold; reset to zero on renewal",
            true,
            false,
        ),
        candidate(
            "state.lower.id",
            "lower",
            "id",
            &[
                R::ArithmeticRegister,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::DerivedEmission,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; prior + 1 on strict renewal",
            true,
            true,
        ),
        candidate(
            "state.lower.value_ticks",
            "lower",
            "value",
            &[
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::CopiedFromInput,
                R::CopiedFromPriorState,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            "copy prior on hold; copy input low on strict renewal",
            true,
            false,
        ),
        candidate(
            "state.lower.birth_bar_index",
            "lower",
            "birth_bar",
            &[
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; reset to current bar index on renewal",
            true,
            false,
        ),
        candidate(
            "state.lower.birth_knowledge_time_ns",
            "lower",
            "birth_knowledge_time",
            &[
                R::CopiedFromInput,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::IdentityBearing,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "copy on hold; reset to current knowledge time on renewal",
            true,
            false,
        ),
        candidate(
            "state.lower.age_bars",
            "lower",
            "age",
            &[
                R::ArithmeticRegister,
                R::CopiedFromPriorState,
                R::PiecewiseAffineUpdate,
                R::TimeBearing,
                R::AuthoritativeStateOutput,
            ],
            "prior + 1 on hold; reset to zero on renewal",
            true,
            false,
        ),
        e(
            "state.close_ticks",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::ObservationO,
                R::CopiedFromInput,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            &["input.close_ticks"],
            "copies current close; not read by the next transition",
            false,
            false,
            "CommittedState.close",
        ),
        e(
            "state.upper_giveback_ticks",
            S::KernelState,
            &[C::MutableCarriedState, C::DerivedWithinStep],
            &[
                R::ArithmeticRegister,
                R::PiecewiseAffineUpdate,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            &["next upper value", "input.close_ticks"],
            "max(0, upper value - close)",
            false,
            false,
            "CommittedState.upper_giveback",
        ),
        e(
            "state.lower_giveback_ticks",
            S::KernelState,
            &[C::MutableCarriedState, C::DerivedWithinStep],
            &[
                R::ArithmeticRegister,
                R::PiecewiseAffineUpdate,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            &["next lower value", "input.close_ticks"],
            "max(0, close - lower value)",
            false,
            false,
            "CommittedState.lower_giveback",
        ),
        e(
            "state.range_locations",
            S::KernelState,
            &[C::MutableCarriedState, C::DerivedWithinStep],
            &[
                R::ControlStateQ,
                R::GuardRegister,
                R::ReadFromPriorState,
                R::PiecewiseAffineUpdate,
                R::DerivedEmission,
                R::AuthoritativeStateOutput,
            ],
            &[
                "prior locations",
                "input close/knowledge time",
                "range context",
            ],
            "unavailable before freeze; otherwise three-way rail comparison; prior value appears in transition emission",
            true,
            true,
            "CommittedState.range_locations",
        ),
        e(
            "state.upper_extensions_ticks",
            S::KernelState,
            &[C::MutableCarriedState, C::DerivedWithinStep],
            &[
                R::ArithmeticRegister,
                R::PiecewiseAffineUpdate,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            &["next upper value", "range high", "freeze availability"],
            "unavailable before freeze; otherwise max(0, upper - range high)",
            false,
            false,
            "CommittedState.upper_extensions",
        ),
        e(
            "state.lower_extensions_ticks",
            S::KernelState,
            &[C::MutableCarriedState, C::DerivedWithinStep],
            &[
                R::ArithmeticRegister,
                R::PiecewiseAffineUpdate,
                R::UsedInArithmetic,
                R::AuthoritativeStateOutput,
            ],
            &["next lower value", "range low", "freeze availability"],
            "unavailable before freeze; otherwise max(0, range low - lower)",
            false,
            false,
            "CommittedState.lower_extensions",
        ),
        e(
            "state.window_active",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::ControlStateQ,
                R::GuardRegister,
                R::UsedInGuard,
                R::ConstantUpdate,
                R::AuthoritativeStateOutput,
            ],
            &["init", "admitted step"],
            "false at init; true after each admitted completed observation",
            true,
            false,
            "CommittedState.window_active",
        ),
        e(
            "state.coverage_complete",
            S::KernelState,
            &[C::MutableCarriedState],
            &[
                R::ControlStateQ,
                R::ObservationO,
                R::CopiedFromInput,
                R::AuthoritativeStateOutput,
            ],
            &["input.coverage"],
            "copies current observation coverage classification",
            false,
            true,
            "CommittedState.coverage_complete",
        ),
        e(
            "context.session_id",
            S::ImmutableContext,
            &[C::ImmutableContext, C::ProvenanceOnly],
            &[R::StaticContextC, R::ProvenanceP, R::ProvenanceOnly],
            &["authorized session identity"],
            "stable provenance; not read by transition arithmetic or guards",
            false,
            false,
            "SessionSpec.session_id",
        ),
        e(
            "context.session_start_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
            ],
            &["SessionSpec.start_epoch via G0"],
            "guards first observation and lower session bound",
            true,
            false,
            "SessionSpec.start_epoch",
        ),
        e(
            "context.session_terminal_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
            ],
            &["SessionSpec.terminal_epoch via G0"],
            "guards upper session bound",
            true,
            false,
            "SessionSpec.terminal_epoch",
        ),
        e(
            "context.price_scale",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::ProvenanceP,
            ],
            &["G0 price scale"],
            "validates input and defines ancestor projection",
            true,
            false,
            "G0 PRICE_SCALE",
        ),
        e(
            "context.source_time_resolution_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
                R::ProvenanceP,
            ],
            &["G0 source-time authority"],
            "validates input authority; remains distinct from storage",
            true,
            false,
            "G0 SOURCE_TIME_RESOLUTION_NS",
        ),
        e(
            "context.storage_time_resolution_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
                R::ProvenanceP,
            ],
            &["G0 bridge storage contract"],
            "context validity guard only",
            true,
            false,
            "G0 nanosecond storage",
        ),
        e(
            "context.observation_cadence_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
            ],
            &["G0 M1 cadence"],
            "guards bar duration and inter-observation chronology",
            true,
            false,
            "G0 OBSERVATION_CADENCE_NS",
        ),
        e(
            "context.range.k",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::IdentityBearing,
                R::ProvenanceP,
            ],
            &["RangeObject.k"],
            "validates ordered R01-R30 identity",
            true,
            true,
            "RangeObject.k",
        ),
        e(
            "context.range.high_ticks",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::UsedInArithmetic,
            ],
            &["RangeObject.high via G0"],
            "upper rail comparison and upper-extension operand",
            true,
            false,
            "RangeObject.high",
        ),
        e(
            "context.range.low_ticks",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::UsedInArithmetic,
            ],
            &["RangeObject.low via G0"],
            "lower rail comparison and lower-extension operand",
            true,
            false,
            "RangeObject.low",
        ),
        e(
            "context.range.freeze_commit_time_ns",
            S::ImmutableContext,
            &[C::ImmutableContext],
            &[
                R::StaticContextC,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
            ],
            &["RangeObject.freeze_commit_time via G0"],
            "guards availability of range-relative state",
            true,
            false,
            "RangeObject.freeze_commit_time",
        ),
        input(
            "input.input_authority",
            &[
                R::ControlStateQ,
                R::GuardRegister,
                R::UsedInGuard,
                R::ProvenanceP,
            ],
            "must be G0 bridge or synthetic metrology authority",
            false,
        ),
        input(
            "input.source_row_id",
            &[R::ObservationO, R::ProvenanceP, R::DerivedEmission],
            "copied into observation-commit emission",
            true,
        ),
        input(
            "input.event_time_ns",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
            ],
            "guards session start/bounds and bar duration",
            false,
        ),
        input(
            "input.knowledge_time_ns",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::UsedInGuard,
                R::CopiedFromInput,
                R::TimeBearing,
                R::DerivedEmission,
            ],
            "guards chronology/range availability; copied into state, births, and emissions",
            true,
        ),
        input(
            "input.open_ticks",
            &[R::ObservationO, R::GuardRegister, R::UsedInGuard],
            "OHLC validity comparisons only",
            false,
        ),
        input(
            "input.high_ticks",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::UsedInArithmetic,
                R::CopiedFromInput,
            ],
            "strict upper-renewal comparison and renewed upper value",
            false,
        ),
        input(
            "input.low_ticks",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::UsedInArithmetic,
                R::CopiedFromInput,
            ],
            "strict lower-renewal comparison and renewed lower value",
            false,
        ),
        input(
            "input.close_ticks",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::ArithmeticRegister,
                R::UsedInGuard,
                R::UsedInArithmetic,
                R::CopiedFromInput,
            ],
            "OHLC/rail comparisons; copied to state; giveback operand",
            false,
        ),
        input(
            "input.price_scale",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::UsedInGuard,
                R::ProvenanceP,
            ],
            "must equal authorized context scale",
            false,
        ),
        input(
            "input.source_time_resolution_ns",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
                R::ProvenanceP,
            ],
            "must equal authorized source-time resolution",
            false,
        ),
        input(
            "input.observation_cadence_ns",
            &[
                R::ObservationO,
                R::GuardRegister,
                R::UsedInGuard,
                R::TimeBearing,
                R::ProvenanceP,
            ],
            "must equal authorized M1 cadence",
            false,
        ),
        input(
            "input.coverage",
            &[R::ObservationO, R::CopiedFromInput, R::DerivedEmission],
            "copied to state and observation-commit emission",
            true,
        ),
    ];
    out.extend(emission_elements());
    out
}

fn candidate(
    id: &str,
    side: &str,
    field: &str,
    roles: &[Role],
    update: &str,
    future: bool,
    emission: bool,
) -> ElementRole {
    ElementRole {
        element_id: id.into(),
        surface: Surface::KernelState,
        carry_status: vec![CarryStatus::MutableCarriedState],
        roles: roles.to_vec(),
        origins: vec![
            format!("prior {side} candidate"),
            format!("current {side} renewal branch"),
        ],
        update_or_use: update.into(),
        read_by_future_transition: future,
        used_in_explicit_emission: emission,
        multi_role_collision: false,
        ancestor_binding: format!("CommittedState.{side}.{field}"),
        evaluability: "QUALIFIED".into(),
    }
}

fn input(id: &str, roles: &[Role], use_text: &str, emission: bool) -> ElementRole {
    e(
        id,
        Surface::CurrentInput,
        &[CarryStatus::CurrentInputOnly],
        roles,
        &["G0-qualified CompletedObservation"],
        use_text,
        false,
        emission,
        "CompletedObservation",
    )
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn e(
    id: &str,
    surface: Surface,
    carry: &[CarryStatus],
    roles: &[Role],
    origins: &[&str],
    update: &str,
    future: bool,
    emission: bool,
    ancestor: &str,
) -> ElementRole {
    ElementRole {
        element_id: id.into(),
        surface,
        carry_status: carry.to_vec(),
        roles: roles.to_vec(),
        origins: origins.iter().map(|x| (*x).to_owned()).collect(),
        update_or_use: update.into(),
        read_by_future_transition: future,
        used_in_explicit_emission: emission,
        multi_role_collision: false,
        ancestor_binding: ancestor.into(),
        evaluability: "QUALIFIED".into(),
    }
}
