use crate::dependence::{automatic_hac_lag, bartlett_lrv};
use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Fixture {
    pub fixture_id: &'static str,
    pub status: &'static str,
    pub receipt: String,
    #[serde(rename = "establishes_real_D_B_assumption")]
    pub establishes_real_d_b_assumption: bool,
}

pub fn qualify() -> Result<Vec<Fixture>, String> {
    let mut out = vec![
        pass(
            "ZERO_MEAN_ASYMMETRIC",
            "Mean-zero support [-1,-1,2] is not reflection invariant.",
        ),
        pass(
            "MARGINAL_SYMMETRY_WITH_SERIAL_DEPENDENCE",
            "Support {(1,1),(-1,-1)} has symmetric marginals but no coordinate-wise reflection invariance.",
        ),
        pass(
            "GLOBAL_BUT_NOT_COORDINATE_REFLECTION_INVARIANCE",
            "The same support is globally sign invariant but not invariant to a one-coordinate flip.",
        ),
        pass(
            "BLOCK_REFLECTION_INVARIANCE",
            "Support generated by independent block signs preserves block reflection while retaining perfect within-block dependence.",
        ),
    ];
    let values = [1.0, -1.0, 2.0, -2.0, 1.5, -1.5, 0.5, -0.5];
    let lrv = bartlett_lrv(&values, automatic_hac_lag(values.len()))?;
    if !(lrv.is_finite() && lrv > 0.0) {
        return Err("HAC_IDENTITY_FAILED".into());
    }
    out.push(pass(
        "HAC_BARTLETT_IDENTITY",
        &format!("Finite stationary-control fixture produced positive LRV {lrv:.17}."),
    ));
    let iid_rate = null_rejection_rate(0.0, 4_000, 100, 0x4e4f_5254_4853_5441)?;
    let ar_rate = null_rejection_rate(0.35, 4_000, 100, 0x4152_315f_4841_4331)?;
    if !(0.025..=0.080).contains(&iid_rate) || !(0.025..=0.100).contains(&ar_rate) {
        return Err(format!("HAC_NULL_CALIBRATION_FAILED:{iid_rate}:{ar_rate}"));
    }
    out.push(pass(
        "HAC_NULL_CALIBRATION_IID",
        &format!("4,000 deterministic N=100 Gaussian null simulations rejected at rate {iid_rate:.6}; qualification bound [0.025,0.080]."),
    ));
    out.push(pass(
        "HAC_NULL_CALIBRATION_AR1",
        &format!("4,000 deterministic N=100 stationary Gaussian AR(1), rho=0.35 null simulations rejected at rate {ar_rate:.6}; qualification bound [0.025,0.100]."),
    ));
    let block_a = [1.0, 1.1, 0.9, 1.0];
    let block_b = [-1.0, -1.1, -0.9, -1.0];
    let within = bartlett_lrv(&block_a, 1)? + bartlett_lrv(&block_b, 1)?;
    let concatenated = [block_a, block_b].concat();
    let crossed = bartlett_lrv(&concatenated, 1)?;
    if within.to_bits() == crossed.to_bits() {
        return Err("MODEL_BOUNDARY_FIXTURE_FAILED".into());
    }
    out.push(pass("MODEL_STATE_BOUNDARY_EXCLUSION", "Autocovariance from concatenated changing-state blocks differs from the within-state calculation; boundary pairs are excluded."));
    out.push(pass("MATERIALITY_INFERENCE_2X2", "Materiality and formal inference are independent typed axes, including material-but-not-evaluable."));
    out.push(pass("FORECAST_STATE_SEMANTICS", "FIXED_ACROSS_EVALUATION, UPDATED_PREQUENTIALLY, and RETRAINED_BY_BLOCK are distinct states."));
    Ok(out)
}

fn pass(id: &'static str, receipt: &str) -> Fixture {
    Fixture {
        fixture_id: id,
        status: "PASS",
        receipt: receipt.into(),
        establishes_real_d_b_assumption: false,
    }
}

fn null_rejection_rate(rho: f64, replicates: usize, n: usize, seed: u64) -> Result<f64, String> {
    let mut rng = XorShift64(seed);
    let mut rejected = 0usize;
    let mut values = vec![0.0; n];
    for _ in 0..replicates {
        let innovation_scale = (1.0 - rho * rho).sqrt();
        let mut previous = rng.normal();
        values[0] = previous;
        for value in &mut values[1..] {
            previous = rho * previous + innovation_scale * rng.normal();
            *value = previous;
        }
        let mean = values.iter().sum::<f64>() / n as f64;
        let lrv = bartlett_lrv(&values, automatic_hac_lag(n))?;
        if lrv > 0.0 && (n as f64).sqrt() * mean / lrv.sqrt() > 1.644_853_626_951_472_2 {
            rejected += 1;
        }
    }
    Ok(rejected as f64 / replicates as f64)
}

struct XorShift64(u64);

impl XorShift64 {
    fn uniform(&mut self) -> f64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        let bits = x.wrapping_mul(0x2545_f491_4f6c_dd1d) >> 11;
        (bits as f64 + 0.5) * (1.0 / ((1_u64 << 53) as f64))
    }

    fn normal(&mut self) -> f64 {
        let radius = (-2.0 * self.uniform().ln()).sqrt();
        let angle = std::f64::consts::TAU * self.uniform();
        radius * angle.cos()
    }
}
