use serde_json::{Value, json};

#[allow(clippy::too_many_arguments)]
fn field(
    name: &str,
    inputs: &[&str],
    first: &str,
    update: &str,
    hold: &str,
    reset: &str,
    identity: &str,
    provisional: &str,
    retrospective: bool,
    class: &str,
) -> Value {
    json!({"FIELD_NAME":name,"SOURCE_INPUTS":inputs,"FIRST_DEFINED_AT":first,"EVENT_TIME":"SOURCE_BAR_CLOSE_BOUNDARY","KNOWLEDGE_TIME":"COMPLETED_SOURCE_BAR_CLOSE; FORMING_DISPLAY_AS_EXPLICITLY_NOTED","UPDATE_RULE":update,"HOLD_RULE":hold,"RESET_RULE":reset,"IDENTITY_RULE":identity,"MISSING_BAR_BEHAVIOR":"FAIL_CLOSED; SENTINEL_PATH_GAP","GAP_BEHAVIOR":"COVERAGE_FALSE_AND_NO_COMPLETE_PATH_ASSERTION","RELOAD_BEHAVIOR":"DETERMINISTIC_HISTORY_RECONSTRUCTION","REPLAY_BEHAVIOR":"DETERMINISTIC_COMPLETED_BAR_FOLD","PROVISIONAL_OR_COMMITTED":provisional,"RETROSPECTIVE_DEPENDENCE":retrospective,"EPISTEMIC_CLASS":class})
}

pub fn sentinel_field_registry() -> Value {
    let mut fields = vec![
        field(
            "UpperExtremeSentinel",
            &["forming_or_completed_bar_high", "prior_upper_committed"],
            "FIRST_WINDOW_BAR",
            "max(prior, observed_high)",
            "hold prior running maximum",
            "session/window reset",
            "highest observed high so far; never terminal-session claim",
            "FORMING_BAR_PROVISIONAL_OR_COMPLETED_BAR_COMMITTED",
            false,
            "DISPLAY_ONLY",
        ),
        field(
            "LowerExtremeSentinel",
            &["forming_or_completed_bar_low", "prior_lower_committed"],
            "FIRST_WINDOW_BAR",
            "min(prior, observed_low)",
            "hold prior running minimum",
            "session/window reset",
            "lowest observed low so far; never terminal-session claim",
            "FORMING_BAR_PROVISIONAL_OR_COMPLETED_BAR_COMMITTED",
            false,
            "DISPLAY_ONLY",
        ),
        field(
            "UpperExtremeCommitted",
            &["completed_bar_high", "prior_upper_committed"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "strict running maximum",
            "equality and lower highs hold",
            "session reset",
            "H_t=max completed highs through t",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerExtremeCommitted",
            &["completed_bar_low", "prior_lower_committed"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "strict running minimum",
            "equality and higher lows hold",
            "session reset",
            "L_t=min completed lows through t",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "UpperExtremeBirthTime",
            &["completed_bar_close", "strict_upper_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "replace with committing bar close on strict renewal",
            "hold active candidate birth",
            "session reset",
            "knowledge time, not intrabar occurrence time",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerExtremeBirthTime",
            &["completed_bar_close", "strict_lower_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "replace with committing bar close on strict renewal",
            "hold active candidate birth",
            "session reset",
            "knowledge time, not intrabar occurrence time",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "NewUpperExtremeFlag",
            &["completed_bar_high", "prior_upper_committed"],
            "EACH_COMPLETED_WINDOW_BAR",
            "one iff strict new upper extreme",
            "zero otherwise",
            "session reset",
            "equality is not renewal",
            "COMPLETED_BAR_EVENT",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "NewLowerExtremeFlag",
            &["completed_bar_low", "prior_lower_committed"],
            "EACH_COMPLETED_WINDOW_BAR",
            "one iff strict new lower extreme",
            "zero otherwise",
            "session reset",
            "equality is not renewal",
            "COMPLETED_BAR_EVENT",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "UpperExtremeAgeBars",
            &["completed_bar_commit", "upper_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "zero on renewal else increment once per completed observation",
            "unchanged on intrabar recalculation",
            "session reset",
            "completed observations since active candidate birth",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerExtremeAgeBars",
            &["completed_bar_commit", "lower_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "zero on renewal else increment once per completed observation",
            "unchanged on intrabar recalculation",
            "session reset",
            "completed observations since active candidate birth",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "UpperGivebackClose",
            &["upper_sentinel", "current_close"],
            "FIRST_WINDOW_BAR",
            "max(0,upper-close)",
            "recompute at observation",
            "session reset",
            "instrument identity only",
            "PROVISIONAL_ON_FORMING_BAR; COMMITTED_ON_COMPLETED_BAR",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerGivebackClose",
            &["lower_sentinel", "current_close"],
            "FIRST_WINDOW_BAR",
            "max(0,close-lower)",
            "recompute at observation",
            "session reset",
            "instrument identity only",
            "PROVISIONAL_ON_FORMING_BAR; COMMITTED_ON_COMPLETED_BAR",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "UpperExtensionFromRange",
            &["upper_sentinel", "frozen_range_high", "GeometryKnownFlag"],
            "RANGE_FREEZE_COMMIT",
            "max(0,upper-range_high)",
            "unavailable before geometry",
            "session reset",
            "range authority is causal frozen geometry",
            "PROVISIONAL_ON_FORMING_BAR; COMMITTED_ON_COMPLETED_BAR",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerExtensionFromRange",
            &["lower_sentinel", "frozen_range_low", "GeometryKnownFlag"],
            "RANGE_FREEZE_COMMIT",
            "max(0,range_low-lower)",
            "unavailable before geometry",
            "session reset",
            "range authority is causal frozen geometry",
            "PROVISIONAL_ON_FORMING_BAR; COMMITTED_ON_COMPLETED_BAR",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "UpperExtremeCandidateId",
            &["strict_upper_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "increment exactly one on strict renewal",
            "hold on equality/ordinary/intrabar observation",
            "session reset",
            "contiguous sequence beginning at one",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "LowerExtremeCandidateId",
            &["strict_lower_renewal"],
            "FIRST_COMPLETED_WINDOW_BAR",
            "increment exactly one on strict renewal",
            "hold on equality/ordinary/intrabar observation",
            "session reset",
            "contiguous sequence beginning at one",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "SentinelWindowActive",
            &["actual_range_start", "area_close_commit", "bar_time"],
            "VALID_RANGE_START",
            "one inside authorized observation window",
            "zero outside",
            "session reset",
            "window membership only",
            "CAUSAL_CURRENT",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "SentinelCoverageFlag",
            &["expected_bar_spacing", "continuity_contract"],
            "FIRST_WINDOW_BAR",
            "one while path continuity qualified; zero after gap",
            "fail closed after gap",
            "session reset",
            "does not repair unseen path",
            "CAUSAL_CURRENT",
            false,
            "CAUSAL_CURRENT",
        ),
    ];
    fields.extend([
        field(
            "CurrentUpperCandidate",
            &[
                "UpperExtremeCandidateId",
                "UpperExtremeCommitted",
                "UpperExtremeBirthTime",
                "UpperExtremeAgeBars",
            ],
            "FIRST_COMPLETED_WINDOW_BAR",
            "replace atomically on strict upper renewal",
            "hold constituent identity between renewals",
            "session reset",
            "typed aggregate of current upper candidate fields",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "CurrentLowerCandidate",
            &[
                "LowerExtremeCandidateId",
                "LowerExtremeCommitted",
                "LowerExtremeBirthTime",
                "LowerExtremeAgeBars",
            ],
            "FIRST_COMPLETED_WINDOW_BAR",
            "replace atomically on strict lower renewal",
            "hold constituent identity between renewals",
            "session reset",
            "typed aggregate of current lower candidate fields",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "CandidatePredecessorId",
            &["candidate_id", "strict_renewal_order"],
            "CANDIDATE_BIRTH",
            "previous same-side candidate",
            "immutable",
            "session reset",
            "neutral genealogy edge",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "CandidateSuccessorId",
            &["later_strict_renewal"],
            "SUPERSESSION_COMMIT",
            "next same-side candidate",
            "unknown until supersession",
            "session reset",
            "causal when successor commits",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "CompletedCandidateLifetime",
            &["birth_knowledge_time", "superseded_time"],
            "SUPERSESSION_COMMIT",
            "superseded_time-birth_knowledge_time",
            "unavailable while active",
            "session reset",
            "completed only after supersession",
            "COMPLETED_RETROSPECTIVE_TO_CANDIDATE_LIFECYCLE",
            true,
            "RETROSPECTIVE_SIDECAR",
        ),
        field(
            "TerminalSurvivor",
            &["active_candidate_at_session_boundary"],
            "SESSION_TERMINATION_BOUNDARY",
            "label active side candidate",
            "unavailable before boundary",
            "session reset",
            "one surviving strict candidate per side only with complete coverage",
            "RETROSPECTIVE_SIDECAR",
            true,
            "RETROSPECTIVE_SIDECAR",
        ),
        field(
            "FinalSessionCandidateMultiplicity",
            &["complete_candidate_genealogy"],
            "SESSION_TERMINATION_BOUNDARY",
            "count final genealogy",
            "unavailable before boundary",
            "session reset",
            "not causal at candidate birth",
            "RETROSPECTIVE_SIDECAR",
            true,
            "RETROSPECTIVE_SIDECAR",
        ),
        field(
            "RangeLocationVector",
            &["completed_close", "causally_frozen_R01_to_R30"],
            "EACH_RANGE_FREEZE_COMMIT",
            "strict ABOVE/BELOW else IN_ZONE",
            "unavailable for unfrozen range",
            "session reset",
            "thirty peer range relations",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "OutsideRunLength",
            &["range_location_sequence"],
            "SECOND_ELIGIBLE_COMPLETED_OBSERVATION",
            "increment while same outside side; reset otherwise",
            "unavailable before range freeze",
            "session reset",
            "derived from causal location tape",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "ExcursionCount",
            &["range_location_transitions"],
            "FIRST_OUTSIDE_TRANSITION",
            "increment on entry into ABOVE or BELOW run",
            "hold otherwise",
            "session reset",
            "causal run count",
            "COMPLETED_BAR_COMMITTED",
            false,
            "CAUSAL_CURRENT",
        ),
        field(
            "GrammarStateAndEvent",
            &["qualified_grammar_stream"],
            "GRAMMAR_STREAM_AVAILABLE",
            "existing grammar contract",
            "existing grammar contract",
            "session reset",
            "not reconstructed when observer stream absent",
            "COMPLETED_BAR_COMMITTED",
            false,
            "NOT_EVALUABLE",
        ),
    ]);
    json!({"schema":"SENTINEL_FIELD_SEMANTICS_REGISTRY_V1","source_kind":"ARTIFACT_DECLARED","fields":fields,"causal_field_admission_rule":"DETERMINISTIC_COMPLETED_BAR_SEMANTICS_REQUIRED","excluded_until_repaired_or_available":["GrammarStateAndEvent"],"status":"QUALIFIED_WITH_TYPED_EXCLUSION"})
}

pub fn provisional_contract() -> Value {
    json!({"schema":"PROVISIONAL_VS_COMMITTED_STATE_CONTRACT_V1","source_kind":"ARTIFACT_DECLARED","forming_bar":{"upper_lower_sentinel":"MAY_MOVE_PROVISIONALLY","giveback_extension":"MAY_FOLLOW_PROVISIONAL_SENTINEL","candidate_id":"MUST_NOT_CHANGE","birth_time":"MUST_NOT_CHANGE","age":"MUST_NOT_CHANGE","genealogy":"MUST_NOT_CHANGE"},"completed_bar":{"strict_renewal":"MAY_COMMIT","candidate_identity":"AUTHORITATIVE","birth_time":"BAR_CLOSE_KNOWLEDGE_TIME","age":"AUTHORITATIVE"},"D_A_atlas":"COMPLETED_BAR_COMMITTED_ONLY"})
}

pub fn causal_retrospective_ledger() -> Value {
    json!({"schema":"CAUSAL_VS_RETROSPECTIVE_LEDGER_V1","source_kind":"ARTIFACT_DECLARED","causal_current":["active_candidate_ids","candidate_values","birth_knowledge_times","candidate_ages","committed_extremes","givebacks","causally_available_range_locations","causally_available_range_extensions","window_active","coverage"],"retrospective_sidecars":["terminal_survivor","terminal_label_known_at","completed_lifetime","final_session_candidate_multiplicity","terminal_lineage_attributes"],"display_only":["forming_bar_upper_sentinel","forming_bar_lower_sentinel"],"forbidden_in_causal_state":["terminal_survivor","final_session_candidate_multiplicity","future_outcomes"]})
}

pub fn genealogy_spec() -> Value {
    json!({"schema":"RUNNING_EXTREME_GENEALOGY_SPEC_V1","source_kind":"ARTIFACT_DECLARED","scientific_ontology":"RUNNING_EXTREME_RENEWAL_GENEALOGY","sides":["UPPER","LOWER"],"node_fields":["candidate_id","side","birth_bar","birth_knowledge_time","candidate_value","causal_age_at_observation"],"causal_edge_fields":["predecessor_id","successor_id","superseded_time"],"retrospective_sidecars":["completed_lifetime","terminal_survivor","terminal_label_known_at","final_multiplicity"],"strictness":"EQUAL_EXTREMA_PRESERVE_ACTIVE_CANDIDATE","id_rule":"FIRST_ID_ONE; STRICT_RENEWAL_INCREMENTS_EXACTLY_ONE; SESSION_RESET_ONLY","forbidden_semantics":["TREND","PRESSURE","MOMENTUM","REJECTION","BREAKOUT_QUALITY"]})
}

pub fn primitive_transition_grammar() -> Value {
    json!({"schema":"PRIMITIVE_TRANSITION_GRAMMAR_V1","source_kind":"ARTIFACT_DECLARED","candidate_events":["NEW_UPPER_EXTREME","NEW_LOWER_EXTREME","UPPER_CANDIDATE_ID_CHANGE","LOWER_CANDIDATE_ID_CHANGE"],"location_event_template":"R{k}_LOCATION_{PREVIOUS}_TO_{CURRENT}","location_states":["IN_ZONE","ABOVE","BELOW"],"initial_location_template":"R{k}_LOCATION_INITIAL_{CURRENT}","same_state_transitions_retained":true,"knowledge_time":"COMPLETED_BAR_CLOSE","interpretive_labels_forbidden":["FAILED_ABOVE","FAILED_BELOW","REJECTION","BREAKOUT"]})
}

pub fn event_tape_specs() -> (Value, Value) {
    let semantic = json!({"schema":"SEMANTIC_EVENT_TAPE_SPEC_V1","source_kind":"ARTIFACT_DECLARED","representation_id":"SEMANTIC_TRANSITION_TAPE_V1","payload":["EVENT_TYPE_ONLY","RANGE_K_WHERE_APPLICABLE"],"ordinary_observation_commits":"OMITTED","exact_price_payload":"OMITTED","exact_timing":"OMITTED","expected_state_reconstruction":"NON_RECONSTRUCTIBLE","purpose":"MINIMAL_EVENT_MORPHOLOGY"});
    let source = json!({"schema":"EVENT_SOURCE_TAPE_SPEC_V1","source_kind":"ARTIFACT_DECLARED","representation_id":"EVENT_SOURCE_TAPE_V1","events":["OBSERVATION_COMMIT","NEW_UPPER_EXTREME","NEW_LOWER_EXTREME","RANGE_LOCATION_TRANSITION"],"observation_commit_payload":["relative_bar_index","event_time","knowledge_time","high","low","close"],"renewal_payload":["side","candidate_id","previous_value","new_value","birth_knowledge_time"],"static_fold_context":["SESSION_BOUNDARY","R01_TO_R30_FROZEN_GEOMETRY"],"bar_open_price":"OMITTED","intrabar_order":"NOT_OBSERVED","expected_state_reconstruction":"RECONSTRUCTIBLE_WITH_DECLARED_CONTEXT","purpose":"DETERMINISTIC_EVENT_SOURCING"});
    (semantic, source)
}

pub fn state_specs() -> (Value, Value) {
    let current = json!({"schema":"CURRENT_SENTINEL_STATE_SPEC_V1","source_kind":"ARTIFACT_DECLARED","representation_id":"CURRENT_SENTINEL_STATE_V1","fields":["bar_index","knowledge_time","current_upper_candidate_id","current_upper_value","current_upper_birth_bar","current_upper_birth_knowledge_time","current_upper_age_bars","current_lower_candidate_id","current_lower_value","current_lower_birth_bar","current_lower_birth_knowledge_time","current_lower_age_bars","completed_close","upper_giveback","lower_giveback","R01_to_R30_location_vector_where_frozen","R01_to_R30_upper_extension_where_frozen","R01_to_R30_lower_extension_where_frozen","window_active","coverage"],"provisional_fields_included":false,"retrospective_fields_included":false,"terminal_survivor_included":false,"final_multiplicity_included":false});
    let reduced = json!({"schema":"REDUCED_SENTINEL_GEOMETRY_SPEC_V1","source_kind":"ARTIFACT_DECLARED","representation_id":"REDUCED_SENTINEL_GEOMETRY_V1","fields":["current_upper_value","current_lower_value","upper_giveback","lower_giveback","R01_to_R30_location_vector_where_frozen","R01_to_R30_upper_extension_where_frozen","R01_to_R30_lower_extension_where_frozen","window_active","coverage"],"discarded_from_current_state":["candidate_ids","birth_bars","birth_knowledge_times","candidate_ages"],"relation_to_current_state":"LOSSY_QUOTIENT"});
    (current, reduced)
}
