use crate::model::{InvariantLanguage, MachineryPermission, PropertyRecord};

const NO_THEOREM: &[&str] = &["NO_APPLICABLE_TRANSFER_THEOREM_EARNED"];
const NO_REDUCTION: &str = "NO_EFFECTIVE_REDUCTION_EARNED";
const EVIDENCE: &[&str] = &[
    "SEALED_SEMANTIC_AUTHORITY",
    "LITERATURE_THEOREM",
    "ALGEBRAIC_PROOF",
    "EXECUTABLE_CERTIFICATE",
    "SYNTHETIC_VALIDATION_ONLY",
];

pub fn property_records() -> Vec<PropertyRecord> {
    vec![
        PropertyRecord {
            property_id: "REACHABILITY",
            problem_signature_id: "G7_REACH_SYMBOLIC_CONFIGURATION_V1",
            semantic_target: "Membership in context-indexed K_reach(C), T_reach(C), or P_exec(C)",
            semantic_authority_source: "G3_SOUND_REACHABILITY_SANDWICH",
            fixed_parameters: &["G1_KERNEL", "G3_CONTEXT_AUTHORITY", "G3_INPUT_LANGUAGE"],
            variable_axes: &["CONTEXT", "SYMBOLIC_TARGET_KIND", "SYMBOLIC_TARGET"],
            promise_domain: "AUTHORIZED_G3_CONTEXT_AND_KERNEL_SEMANTICS",
            input_encoding: "TYPED_CONTEXT_PLUS_SYMBOLIC_CONFIGURATION_TRANSITION_OR_PREFIX",
            effective_presentation_status: "UPPER_ENVELOPE_EFFECTIVE_EXACT_TRUE_SET_NOT_EARNED",
            analysis_route_id: "G7_REACHABILITY_COMPOSITIONAL_V1",
            formalism_fit_status: "WHOLE_KERNEL_FORMALISM_MEMBERSHIP_NOT_EARNED",
            theorem_or_result: "CONSTRUCTIVE_ANCESTRY_IS_EXACT_POSITIVE_CERTIFICATE; GENERAL_TRUTH_STATUS_UNKNOWN",
            theorem_preconditions: NO_THEOREM,
            reduction_direction: NO_REDUCTION,
            reduction_effective: false,
            property_preservation: "NOT_EARNED",
            property_reflection: "NOT_EARNED",
            metatheoretic_status: "UNKNOWN",
            certification_authority: "ONE_SIDED_CERTIFIER_AUTHORIZED",
            search_or_decision_authority: "SOUND_BOUNDED_SEARCH_ONLY",
            certificate_authority: "EXACT_QUALIFIED_ANCESTRY_CERTIFICATE_VERIFIER",
            soundness: "POSITIVE_CERTIFICATE_SOUND; BOUNDED_UNSAT_ONLY_BOUNDED",
            completeness: "NOT_EARNED",
            termination: "CERTIFICATE_VERIFIER_TERMINATES; GENERAL_SEARCH_NOT_GUARANTEED",
            positive_result_authority: "REACHABLE_WITH_VERIFIED_ANCESTRY",
            negative_result_authority: "NONE_FROM_SEARCH_FAILURE; PROVED_G3_EXCLUSION_ONLY",
            approximation_transfer_rule_ids: &[
                "G3_UNDERAPPROX_POSITIVE",
                "G3_OVERAPPROX_UNIVERSAL",
            ],
            failure_boundary: "EXACT_TRUE_REACHABILITY_AND_INPUT_LANGUAGE_NOT_EFFECTIVELY_CHARACTERIZED",
            safe_downstream_use: &[
                "VERIFY_CONSTRUCTIVE_STARTS",
                "BOUNDED_EXPLORATION_WITH_TYPED_UNKNOWN",
            ],
            forbidden_downstream_inference: &[
                "GLOBAL_UNREACHABILITY_FROM_TIMEOUT",
                "EXACT_REACHABILITY_DECIDER",
            ],
            evidence_classes: EVIDENCE,
        },
        PropertyRecord {
            property_id: "INVARIANT_PRESERVATION",
            problem_signature_id: "G7_INVARIANT_LANGUAGE_PARAMETERIZED_V1",
            semantic_target: "Semantic invariance or one-step inductiveness for an explicitly named invariant language",
            semantic_authority_source: "G1_STEP_PLUS_G3_REACHABILITY_SEMANTICS",
            fixed_parameters: &["G1_KERNEL", "INVARIANT_LANGUAGE_ID", "CONTEXT_CLASS"],
            variable_axes: &[
                "FORMULA",
                "SEMANTIC_INVARIANCE_OR_INDUCTIVENESS",
                "TRANSITION_CLASS",
            ],
            promise_domain: "FORMULAS_IN_REGISTERED_LANGUAGE_OVER_AUTHORIZED_CONTEXTS",
            input_encoding: "TYPED_FORMULA_AST_PLUS_SEMANTIC_TARGET_TAG",
            effective_presentation_status: "RESTRICTED_ONE_STEP_ENCODINGS_EFFECTIVE; REACHABLE_DOMAIN_EXACTNESS_NOT_EARNED",
            analysis_route_id: "G7_INVARIANT_LANGUAGE_SPLIT_V1",
            formalism_fit_status: "RESTRICTED_LINEAR_AND_FINITE_CONTROL_SUBROUTES_ONLY",
            theorem_or_result: "RESTRICTED_INDUCTIVENESS_MAY_BE_EXACT; GLOBAL_SEMANTIC_INVARIANCE_UNKNOWN",
            theorem_preconditions: &[
                "EXACT_FORMULA_LANGUAGE_ENCODING",
                "SOUND_TRANSITION_ENCODING",
                "DECLARED_CONTEXT_SCOPE",
            ],
            reduction_direction: "NORTHSTAR_RESTRICTED_INDUCTIVENESS_TO_DECIDABLE_ARITHMETIC_WHEN_PROVEN",
            reduction_effective: true,
            property_preservation: "EARNED_ONLY_PER_REGISTERED_RESTRICTED_ROUTE",
            property_reflection: "EARNED_ONLY_PER_REGISTERED_RESTRICTED_ROUTE",
            metatheoretic_status: "UNKNOWN",
            certification_authority: "RESTRICTED_EXACT_INDUCTIVENESS_CERTIFIER_AUTHORIZED",
            search_or_decision_authority: "BUILD_RESTRICTED_EXACT_DECIDER",
            certificate_authority: "CHECKABLE_INDUCTIVENESS_PROOF_OR_COUNTERTRANSITION",
            soundness: "SOUND_INSIDE_EXPLICIT_LANGUAGE_AND_TRANSITION_SCOPE",
            completeness: "RESTRICTED_ROUTE_ONLY",
            termination: "RESTRICTED_CHECKER_TERMINATES; GLOBAL_SEMANTIC_QUERY_NOT_GUARANTEED",
            positive_result_authority: "INDUCTIVE_IN_NAMED_LANGUAGE_AND_SCOPE",
            negative_result_authority: "NON_INDUCTIVE_WITH_CONCRETE_TRANSITION; NOT_SEMANTICALLY_FALSE_WITHOUT_REACHABILITY",
            approximation_transfer_rule_ids: &["G3_OVERAPPROX_UNIVERSAL"],
            failure_boundary: "INDUCTIVENESS_IS_NOT_SEMANTIC_INVARIANCE_AND_MIXED_TRACE_LANGUAGES_LACK_COMPLETE_ROUTE",
            safe_downstream_use: &[
                "PROVE_LOCAL_INDUCTIVENESS",
                "VERIFY_CONCRETE_COUNTERTRANSITIONS",
            ],
            forbidden_downstream_inference: &[
                "GLOBAL_INVARIANT_DECIDABLE",
                "NON_INDUCTIVE_IMPLIES_REACHABLE_VIOLATION",
            ],
            evidence_classes: EVIDENCE,
        },
        PropertyRecord {
            property_id: "BEHAVIORAL_EQUIVALENCE",
            problem_signature_id: "G7_G6_FIBER_EQUIVALENCE_V1",
            semantic_target: "Exact G6 finite-trace behavioral equivalence inside one qualified fiber",
            semantic_authority_source: "G6_EXACT_SEMANTIC_RELATION",
            fixed_parameters: &["G4_SURFACE", "G5_COUPLING", "G6_CORRESPONDENCE", "G6_FIBER"],
            variable_axes: &["LEFT_QUALIFIED_HISTORY", "RIGHT_QUALIFIED_HISTORY"],
            promise_domain: "COMPARABLE_SAME_FIBER_G3_QUALIFIED_PREFIX_PAIR",
            input_encoding: "TWO_ANCESTRY_BEARING_PREFIXES_PLUS_CONTEXTS_AND_INITIAL_CORRESPONDENCE",
            effective_presentation_status: "FINITE_TRACES_EXECUTABLE; COMPLETE_TRUE_CONTINUATION_LANGUAGE_NOT_EARNED",
            analysis_route_id: "G7_EQUIVALENCE_COMPOSITIONAL_PROOF_V1",
            formalism_fit_status: "NO_SINGLE_FORMALISM_OR_COMPLETE_REDUCTION_EARNED",
            theorem_or_result: "EXACT_SEMANTIC_DEFINITION; DECISION_STATUS_UNKNOWN",
            theorem_preconditions: NO_THEOREM,
            reduction_direction: NO_REDUCTION,
            reduction_effective: false,
            property_preservation: "NOT_EARNED",
            property_reflection: "NOT_EARNED",
            metatheoretic_status: "UNKNOWN",
            certification_authority: "ONE_SIDED_UNIVERSAL_PROOF_CERTIFIER_IF_PROOF_COVERS_SOUND_UPPER_ENVELOPE",
            search_or_decision_authority: "NO_DECISION_AUTHORITY",
            certificate_authority: "RESTRICTED_PROOF_CERTIFICATE_VERIFIER_ONLY",
            soundness: "UNIVERSAL_PROOF_OVER_SOUND_SUPERSET_TRANSFERS_DOWNWARD",
            completeness: "NOT_EARNED",
            termination: "CERTIFICATE_VERIFICATION_TERMINATES; EQUIVALENCE_SEARCH_NOT_GUARANTEED",
            positive_result_authority: "EQUIVALENT_ONLY_WITH_ACCEPTED_SCOPE-COMPLETE_PROOF",
            negative_result_authority: "ONLY_BY_VERIFIED_FINITE_SEPARATOR",
            approximation_transfer_rule_ids: &["G3_G5_SOUND_SUPERSET_UNIVERSAL"],
            failure_boundary: "G5_TRUE_LANGUAGE_AND_G3_TRUE_REACHABLE_DOMAIN_ARE_NOT EXACTLY CHARACTERIZED",
            safe_downstream_use: &[
                "VERIFY_SCOPE-COMPLETE_UNIVERSAL_PROOF",
                "SEARCH_FOR_SEPARATOR_WITHOUT_EQUIVALENCE_DEFAULT",
            ],
            forbidden_downstream_inference: &[
                "BOUNDED_UNSAT_MEANS_EQUIVALENT",
                "NO_WITNESS_FOUND_MEANS_EQUIVALENT",
            ],
            evidence_classes: EVIDENCE,
        },
        PropertyRecord {
            property_id: "BEHAVIORAL_NON_EQUIVALENCE",
            problem_signature_id: "G7_G6_FIBER_NON_EQUIVALENCE_V1",
            semantic_target: "Failure of exact G6 equivalence inside a qualified comparison fiber",
            semantic_authority_source: "G6_EXACT_SEMANTIC_RELATION_AND_FINITE_HORIZON",
            fixed_parameters: &["G4_SURFACE", "G5_COUPLING", "G6_CORRESPONDENCE", "G6_FIBER"],
            variable_axes: &["LEFT_QUALIFIED_HISTORY", "RIGHT_QUALIFIED_HISTORY"],
            promise_domain: "COMPARABLE_SAME_FIBER_CONSTRUCTIVELY_QUALIFIED_STARTS",
            input_encoding: "PAIR_PLUS_EFFECTIVELY_ENUMERABLE_FINITE_RELATIVE_TOKEN_WORD",
            effective_presentation_status: "EFFECTIVE_FOR_EACH_FINITE_TOKEN_WORD_AND_CONCRETE_REALIZATION",
            analysis_route_id: "G7_FINITE_SEPARATOR_ENUMERATION_V1",
            formalism_fit_status: "DIRECT_G6_SEMANTIC_CERTIFICATE_ROUTE",
            theorem_or_result: "NON_EQUIVALENCE_IFF_FINITE_PROTECTED_SEPARATOR_WITHIN_FIBER",
            theorem_preconditions: &[
                "SAME_LAWFUL_FIBER",
                "CONSTRUCTIVE_STARTS",
                "TERMINATING_REALIZATION",
                "DECIDABLE_MISMATCH",
            ],
            reduction_direction: "NON_EQUIVALENCE_TO_AND_FROM_FINITE_SEPARATOR_EXISTENCE",
            reduction_effective: true,
            property_preservation: "PROVEN_WITHIN_G6_FIBER",
            property_reflection: "PROVEN_WITHIN_G6_FIBER",
            metatheoretic_status: "RECOGNIZABLE",
            certification_authority: "ONE_SIDED_CERTIFIER_AUTHORIZED",
            search_or_decision_authority: "BUILD_ONE_SIDED_CERTIFICATE_SEARCH",
            certificate_authority: "EXACT_FINITE_SEPARATOR_CERTIFICATE_VERIFIER",
            soundness: "SOUND_FOR_ACCEPTED_CERTIFICATES",
            completeness: "ENUMERATION_COMPLETE_FOR_FINITE_TOKEN WORDS; TERMINATION_ONLY_IF_WITNESS_EXISTS",
            termination: "VERIFIER_TERMINATES; SEARCH SEMI-DECIDES POSITIVE INSTANCES",
            positive_result_authority: "BEHAVIORALLY_NON_EQUIVALENT_WITHIN_FIBER",
            negative_result_authority: "NONE_FROM NONTERMINATION OR BOUND",
            approximation_transfer_rule_ids: &["G5_TRUE_PRESENTABILITY_REQUIRED"],
            failure_boundary: "OUTSIDE_FIBER_IS_NON_COMPARABLE_NOT_NON_EQUIVALENT",
            safe_downstream_use: &["ENUMERATE_AND_VERIFY_FINITE_SEPARATORS"],
            forbidden_downstream_inference: &[
                "NON_COMPARABILITY_IS_NON_EQUIVALENCE",
                "SEARCH_EXHAUSTION_WITHOUT_FINITE_DOMAIN_IS_EQUIVALENCE",
            ],
            evidence_classes: EVIDENCE,
        },
        PropertyRecord {
            property_id: "DISTINGUISHING_WITNESS_EXISTENCE",
            problem_signature_id: "G7_FINITE_SEPARATOR_EXISTENCE_V1",
            semantic_target: "Existence of a lawful finite continuation producing a G4 protected mismatch",
            semantic_authority_source: "G4_G5_G6_COMPOSED_SEMANTICS",
            fixed_parameters: &[
                "PAIR",
                "FIBER",
                "COUPLING",
                "CORRESPONDENCE",
                "MISMATCH_PREDICATE",
            ],
            variable_axes: &["FINITE_RELATIVE_TOKEN_SEQUENCE"],
            promise_domain: "CONSTRUCTIVE_SAME_FIBER_STARTS_WITH_EFFECTIVE_G5_REALIZATION",
            input_encoding: "LENGTH_PREFIXED_CANONICAL_SIGNED_INTEGER_TOKEN_SEQUENCE",
            effective_presentation_status: "COUNTABLY_EFFECTIVE_ENUMERATION_AND_TERMINATING_PER-CANDIDATE_VERIFICATION",
            analysis_route_id: "G7_EXPLORER_CERTIFICATE_VERIFIER_V1",
            formalism_fit_status: "DIRECT_EXECUTABLE_CERTIFICATE_ROUTE",
            theorem_or_result: "FINITE_SEPARATOR EXISTENCE IS RECOGNIZABLE ON PROMISE DOMAIN",
            theorem_preconditions: &[
                "EFFECTIVE_TOKEN_ENUMERATION",
                "TERMINATING_REALIZER",
                "TERMINATING_KERNEL",
                "DECIDABLE_PROTECTED_MISMATCH",
            ],
            reduction_direction: "WITNESS_EXISTENCE_TO_EXECUTABLE_CERTIFICATE_ACCEPTANCE",
            reduction_effective: true,
            property_preservation: "PROVEN",
            property_reflection: "PROVEN_FOR_ACCEPTED_CERTIFICATE_SCHEMA",
            metatheoretic_status: "RECOGNIZABLE",
            certification_authority: "ONE_SIDED_CERTIFIER_AUTHORIZED",
            search_or_decision_authority: "BUILD_ONE_SIDED_CERTIFICATE_SEARCH",
            certificate_authority: "EXACT_FINITE_SEPARATOR_CERTIFICATE_VERIFIER",
            soundness: "SOUND",
            completeness: "SEMI-DECISION_COMPLETE_FOR EXISTING FINITE WITNESS UNDER FAIR ENUMERATION",
            termination: "VERIFIER_ALWAYS; EXPLORER ONLY ON POSITIVE INSTANCE",
            positive_result_authority: "FINITE_DISTINGUISHING_WITNESS_EXISTS",
            negative_result_authority: "NONE_FROM FAILURE_TO_FIND",
            approximation_transfer_rule_ids: &["G5_UPPER_ENVELOPE_CANDIDATE_NOT_CERTIFICATE"],
            failure_boundary: "UPPER_ENVELOPE_ONLY_OR_UNQUALIFIED_STARTS CANNOT EARN WITNESS",
            safe_downstream_use: &["HEURISTIC_OR_ENUMERATIVE_EXPLORER_TO_EXACT_VERIFIER"],
            forbidden_downstream_inference: &[
                "TIMEOUT_MEANS_NO_WITNESS",
                "CANDIDATE_IN_U_PLUS_IS_LAWFUL",
            ],
            evidence_classes: EVIDENCE,
        },
        PropertyRecord {
            property_id: "DISTINGUISHING_WITNESS_MINIMALITY",
            problem_signature_id: "G7_GLOBAL_SEPARATOR_MINIMALITY_V1",
            semantic_target: "A verified separator with no strictly cheaper lawful separator under frozen lexicographic cost",
            semantic_authority_source: "G6_DUAL_PROGRESS_AND_G7_WITNESS_COST_CONTRACT",
            fixed_parameters: &["PAIR", "FIBER", "COST_ORDER", "WITNESS_VERIFIER"],
            variable_axes: &["CANDIDATE_SEPARATOR", "STRICT_LOWER_COST_CONE"],
            promise_domain: "VERIFIED_SEPARATOR_FOR_CONSTRUCTIVE_SAME_FIBER_STARTS",
            input_encoding: "CERTIFICATE_PLUS_GLOBAL_LOWER_CONE_EXCLUSION_PROOF",
            effective_presentation_status: "COST_ORDER_EFFECTIVE; GLOBAL_LOWER_CONES MAY BE INFINITE",
            analysis_route_id: "G7_MINIMALITY_LOWER_CONE_V1",
            formalism_fit_status: "GLOBAL_EXCLUSION_ROUTE_NOT_EARNED; FINITE_BOX_RESTRICTION_AVAILABLE",
            theorem_or_result: "GLOBAL MINIMALITY UNKNOWN; EXACT ONLY IN EXPLICIT FINITE TOKEN BOX",
            theorem_preconditions: &[
                "WELL_FOUNDED_COST",
                "EFFECTIVE_LOWER_CONE",
                "COMPLETE_NO-WITNESS DECISION OVER LOWER CONE",
            ],
            reduction_direction: NO_REDUCTION,
            reduction_effective: false,
            property_preservation: "NOT_EARNED_GLOBALLY",
            property_reflection: "NOT_EARNED_GLOBALLY",
            metatheoretic_status: "UNKNOWN",
            certification_authority: "BOUNDED_FINITE_DOMAIN_MINIMALITY_ONLY",
            search_or_decision_authority: "BUILD_RESTRICTED_EXACT_DECIDER",
            certificate_authority: "EXACT_SEPARATOR_VERIFIER_PLUS_FINITE_LOWER_CONE_EXHAUSTION_RECEIPT",
            soundness: "SOUND_ONLY_FOR EXPLICIT FINITE BOX AND FROZEN COST",
            completeness: "RESTRICTED_FINITE_DOMAIN_ONLY",
            termination: "FINITE_BOX CHECK TERMINATES; GLOBAL MINIMALITY NOT GUARANTEED",
            positive_result_authority: "MINIMAL_WITHIN_DECLARED_FINITE_BOX_ONLY",
            negative_result_authority: "CHEAPER VERIFIED WITNESS REFUTES MINIMALITY",
            approximation_transfer_rule_ids: &[],
            failure_boundary: "TOKEN_LENGTH DOES NOT BOUND INTEGER MAGNITUDE; GLOBAL LOWER CONE EXCLUSION NOT EARNED",
            safe_downstream_use: &["REPORT BOUNDED_MINIMAL", "VERIFY CHEAPER COUNTERWITNESS"],
            forbidden_downstream_inference: &[
                "BOUNDED_MINIMAL_IS_GLOBAL_MINIMAL",
                "FIRST_FOUND_IS_MINIMAL",
            ],
            evidence_classes: EVIDENCE,
        },
    ]
}

pub fn invariant_languages() -> Vec<InvariantLanguage> {
    vec![
        InvariantLanguage {
            invariant_language_id: "FINITE_CONTROL_V1",
            syntax: "Boolean combinations of finite control equalities",
            semantic_invariance: "UNKNOWN_WITHOUT_EXACT_REACHABILITY_OR_PROOF",
            inductiveness_checking: "EXACT_BY_FINITE_CASES_WHEN_TRANSITION_PARTITION_COMPLETE",
            authority_boundary: "NAMED_CONTROL_SUBSYSTEM_ONLY",
        },
        InvariantLanguage {
            invariant_language_id: "AFFINE_EQUALITY_V1",
            syntax: "Integer affine equalities",
            semantic_invariance: "UNKNOWN_GLOBALLY",
            inductiveness_checking: "RESTRICTED_EXACT_LINEAR_ARITHMETIC_ROUTE",
            authority_boundary: "PIECEWISE_BRANCHES_AND_CONTEXT_EXPLICIT",
        },
        InvariantLanguage {
            invariant_language_id: "LINEAR_INEQUALITY_V1",
            syntax: "Quantifier-free integer linear inequalities including strict comparisons",
            semantic_invariance: "UNKNOWN_GLOBALLY",
            inductiveness_checking: "RESTRICTED_EXACT_PRESBURGER_OR_SMT_ROUTE_IF_ENCODING_PROVEN",
            authority_boundary: "SOLVER_RESULT_NEEDS_CHECKABLE_CERTIFICATE_OR_TRUSTED_DECISION_CORE",
        },
        InvariantLanguage {
            invariant_language_id: "ORDER_RELATION_V1",
            syntax: "Price/time/order predicates",
            semantic_invariance: "UNKNOWN_GLOBALLY",
            inductiveness_checking: "RESTRICTED_EXACT_CASE_ANALYSIS",
            authority_boundary: "CANONICAL_INTEGER_AND_KNOWLEDGE_TIME_SEMANTICS_ONLY",
        },
        InvariantLanguage {
            invariant_language_id: "GENEALOGICAL_V1",
            syntax: "Candidate identity, predecessor/successor, birth and supersession relations",
            semantic_invariance: "UNKNOWN",
            inductiveness_checking: "RESTRICTED_STRUCTURAL_PROOF_ONLY",
            authority_boundary: "NO_GENERIC_ARITHMETIC_THEOREM_TRANSFER",
        },
        InvariantLanguage {
            invariant_language_id: "TRACE_RELATIONAL_V1",
            syntax: "Properties over finite protected traces and correspondence evolution",
            semantic_invariance: "UNKNOWN",
            inductiveness_checking: "NOT_EVALUABLE_AS_ONE_STEP_STATE_FORMULA_WITHOUT MONITOR CONSTRUCTION",
            authority_boundary: "G6_FINITE_TRACE_ONLY",
        },
        InvariantLanguage {
            invariant_language_id: "MIXED_OBSERVER_V1",
            syntax: "Cross-domain control, arithmetic, chronology, genealogy, rejection and emission formulae",
            semantic_invariance: "UNKNOWN",
            inductiveness_checking: "COMPOSITIONAL_ONLY_WITH PROVEN SEAM RULES",
            authority_boundary: "NO_SINGLE FORMALISM MEMBERSHIP",
        },
    ]
}

pub fn machinery_permissions() -> Vec<MachineryPermission> {
    vec![
        MachineryPermission {
            problem_signature_id: "G7_REACH_SYMBOLIC_CONFIGURATION_V1",
            permissions: &[
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "BUILD_SOUND_BOUNDED_EXPLORER",
                "DO_NOT_BUILD_DECISION_CLAIMING_MACHINE",
            ],
            authoritative_output: &["VERIFIED_REACHABLE", "BOUNDED_NOT_FOUND", "UNKNOWN"],
            forbidden_output: &["UNREACHABLE_FROM_SEARCH_FAILURE"],
        },
        MachineryPermission {
            problem_signature_id: "G7_INVARIANT_LANGUAGE_PARAMETERIZED_V1",
            permissions: &[
                "BUILD_RESTRICTED_EXACT_DECIDER",
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "BUILD_SOUND_BOUNDED_EXPLORER",
            ],
            authoritative_output: &[
                "INDUCTIVE_IN_NAMED_SCOPE",
                "CONCRETE_NONINDUCTIVE_TRANSITION",
                "UNKNOWN_SEMANTIC_INVARIANCE",
            ],
            forbidden_output: &["GLOBAL_INVARIANT_DECIDABLE"],
        },
        MachineryPermission {
            problem_signature_id: "G7_G6_FIBER_EQUIVALENCE_V1",
            permissions: &[
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "BUILD_SOUND_BOUNDED_EXPLORER",
                "DO_NOT_BUILD_DECISION_CLAIMING_MACHINE",
            ],
            authoritative_output: &["EQUIVALENT_WITH_ACCEPTED UNIVERSAL PROOF", "UNKNOWN"],
            forbidden_output: &["EQUIVALENT_FROM_BOUNDED_UNSAT"],
        },
        MachineryPermission {
            problem_signature_id: "G7_G6_FIBER_NON_EQUIVALENCE_V1",
            permissions: &[
                "BUILD_ONE_SIDED_CERTIFICATE_SEARCH",
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "BUILD_HEURISTIC_EXPLORER_WITH_AUTHORITATIVE_VERIFIER",
            ],
            authoritative_output: &[
                "BEHAVIORALLY_NON_EQUIVALENT_WITH VERIFIED SEPARATOR",
                "UNKNOWN",
            ],
            forbidden_output: &["EQUIVALENT_FROM_NO_WITNESS"],
        },
        MachineryPermission {
            problem_signature_id: "G7_FINITE_SEPARATOR_EXISTENCE_V1",
            permissions: &[
                "BUILD_ONE_SIDED_CERTIFICATE_SEARCH",
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "BUILD_HEURISTIC_EXPLORER_WITH_AUTHORITATIVE_VERIFIER",
            ],
            authoritative_output: &["VERIFIED_FINITE_SEPARATOR", "UNKNOWN"],
            forbidden_output: &["NO_WITNESS_FROM_TIMEOUT"],
        },
        MachineryPermission {
            problem_signature_id: "G7_GLOBAL_SEPARATOR_MINIMALITY_V1",
            permissions: &[
                "BUILD_RESTRICTED_EXACT_DECIDER",
                "BUILD_EXACT_CERTIFICATE_VERIFIER",
                "DO_NOT_BUILD_DECISION_CLAIMING_MACHINE",
            ],
            authoritative_output: &[
                "MINIMAL_WITHIN_DECLARED_FINITE_BOX",
                "CHEAPER_VERIFIED_WITNESS",
                "UNKNOWN_GLOBAL_MINIMALITY",
            ],
            forbidden_output: &[
                "GLOBAL_MINIMAL_FROM_FIRST_FOUND",
                "GLOBAL_MINIMAL_FROM_BOUNDED_EXHAUSTION",
            ],
        },
    ]
}
