use crate::authority::{
    FIBER_CERTIFICATE_SCHEMA, SEPARATOR_SCHEMA_ID, SEPARATOR_SCHEMA_VERSION,
    UNIVERSAL_PROOF_SYSTEM_ID, authority_bundle_hash, verifier_contract_hash,
};
use crate::{AUTHORITY, G3_ROOT, G4_ROOT, G5_ROOT, G6_ROOT, G7_ROOT, RESULT, THETA_STAR_ID};
use serde_json::{Value, json};

pub fn contracts() -> Vec<(&'static str, Value)> {
    vec![
        (
            "WITNESS_LABORATORY_QUALIFICATION_V1.json",
            json!({
                "schema":"G8_WITNESS_LABORATORY_QUALIFICATION_V1","result":RESULT,"authority":AUTHORITY,
                "scope":"SYNTHETIC_AND_FORMALLY_UNDERSTOOD_SYSTEMS_ONLY","real_04A_pair_execution":false,
                "governing_law":"EXPLORER_MAY_PROPOSE_CERTIFICATE_MAY_CLAIM_ONLY_VERIFIER_MAY_AUTHORIZE",
                "three_vocabularies_mechanically_separate":true
            }),
        ),
        (
            "AUTHORITY_VERDICT_VOCABULARY_V1.json",
            json!({
                "schema":"G8_AUTHORITY_VERDICT_VOCABULARY_V1","source":"G7_CLOSED_AUTHORIZED_VOCABULARY",
                "values":["VERIFIED_REACHABLE","BOUNDED_NOT_FOUND","UNKNOWN","INDUCTIVE_IN_NAMED_SCOPE","CONCRETE_NONINDUCTIVE_TRANSITION","UNKNOWN_SEMANTIC_INVARIANCE","EQUIVALENT_WITH_ACCEPTED_UNIVERSAL_PROOF","BEHAVIORALLY_NON_EQUIVALENT_WITH_VERIFIED_SEPARATOR","VERIFIED_FINITE_SEPARATOR","MINIMAL_WITHIN_DECLARED_FINITE_BOX","CHEAPER_VERIFIED_WITNESS","UNKNOWN_GLOBAL_MINIMALITY"],
                "forbidden_aliases":["EXACT_EQUIVALENCE","EXACT_MINIMAL_WITNESS","NOT_DECIDABLE_UNDER_CURRENT_FORMALISM"]
            }),
        ),
        (
            "LAB_ARTIFACT_CLASS_VOCABULARY_V1.json",
            json!({
                "schema":"G8_LAB_ARTIFACT_CLASS_VOCABULARY_V1","values":["CANONICAL_FIRST_WITNESS","SHRUNK_WITNESS","FINITE_BOX_MINIMUM","UNIVERSAL_PROOF_CERTIFICATE","REACHABILITY_CERTIFICATE","OTHER_REGISTERED_ARTIFACT"],
                "semantic_strength":"NONE_WITHOUT_VERIFIER_ACCEPTANCE"
            }),
        ),
        (
            "SEARCH_STATUS_VOCABULARY_V1.json",
            json!({
                "schema":"G8_SEARCH_STATUS_VOCABULARY_V1","values":["NOT_STARTED","RUNNING","BOUNDED_DOMAIN_EXHAUSTED","TIMEOUT","RESOURCE_EXHAUSTED","INTERRUPTED","ABORTED","COMPLETE"],
                "scientific_verdict":false,"timeout_implies":"NOTHING"
            }),
        ),
        (
            "QUALIFIED_COMPARISON_FIBER_CERTIFICATE_V1.json",
            json!({
                "schema":FIBER_CERTIFICATE_SCHEMA,"required":["source","fiber_id","left_machine_id","right_machine_id","construction_proof_hash"],
                "authorized_qualification_sources":["G6_CONSTRUCTION_BY_PROOF","SYNTHETIC_FINITE_SYSTEM_CONSTRUCTION","OTHER_EXPLICIT_G7_AUTHORITY"],
                "appearance_based_inference":false,"missing_result":{"fiber_status":"MISSING","authority_verdict":"UNKNOWN"}
            }),
        ),
        (
            "VERIFIER_TRUSTED_COMPUTING_BASE_V1.json",
            json!({
                "schema":"G8_VERIFIER_TRUSTED_COMPUTING_BASE_V1","verifier_contract_hash":verifier_contract_hash(),
                "components":["SEALED_G3_G7_ROOT_BINDING","CANONICAL_CERTIFICATE_PARSER","CHECKED_INTEGER_SEMANTICS","SYNTHETIC_DETERMINISTIC_KERNEL","FIBER_PROOF_RECOMPUTATION","G4_PROTECTED_MISMATCH_RECOMPUTATION","FINITE_PRODUCT_PROOF_KERNEL","CANONICAL_HASH"],
                "excludes":["EXPLORER_STATE","EXPLORER_CACHE","HEURISTIC_RANKING","LEARNED_MODEL","RANDOM_STATE","CANDIDATE_GENERATOR","SEARCH_SUCCESS_OR_FAILURE","REFERENCE_ORACLE"]
            }),
        ),
        (
            "VERIFIER_DEPENDENCY_MANIFEST_V1.json",
            json!({
                "schema":"G8_VERIFIER_DEPENDENCY_MANIFEST_V1",
                "verifier_module_reads":["authority","model","ranking","bitvec","hashbrown"],
                "verifier_imports_explorer":false,"explorer_imports_verifier":true,
                "oracle_imports_verifier":false,"verifier_imports_oracle":false
            }),
        ),
        (
            "VERIFIER_SOUNDNESS_ARGUMENT_V1.json",
            json!({
                "schema":"G8_VERIFIER_SOUNDNESS_ARGUMENT_V1","status":"PROVED_BY_COMPOSITIONAL_SEMANTIC_ARGUMENT",
                "theorem":"V(c)=ACCEPT IMPLIES c proves its registered claim",
                "separator_argument":["EXACT_LINEAGE_EQUALITY","RECOMPUTED_FIBER_CONSTRUCTION_PROOF","FROZEN_COMPARISON_IDS","VALID_STARTS","TOKEN_SOURCE_VALIDITY","DETERMINISTIC_TOTAL_FOLD_OR_TYPED_REJECTION","INDEPENDENT_DERIVED_TRACE_RECOMPUTATION","PROTECTED_MISMATCH_EXISTS"],
                "universal_argument":"FINITE_RELATION_CONTAINS_INITIAL_PAIR_MATCHES_OUTPUTS_AND_IS_CLOSED_UNDER_EVERY_FINITE_ALPHABET_SYMBOL; INDUCTION_ON_WORD_LENGTH",
                "fixtures_are_proof":false,"completeness":"SEPARATELY_RESTRICTED"
            }),
        ),
        (
            "CERTIFICATE_FIELD_ROLE_REGISTRY_V1.json",
            json!([
                {"field":"authority_binding","role":"PRIMITIVE_EVIDENCE"},{"field":"qualified_histories_or_synthetic_machines","role":"PRIMITIVE_EVIDENCE"},
                {"field":"fiber_certificate","role":"PRIMITIVE_EVIDENCE"},{"field":"neutral_token_sequence","role":"PRIMITIVE_EVIDENCE"},
                {"field":"side_specific_realizations","role":"DERIVED_CLAIM"},{"field":"per_token_presentability","role":"DERIVED_CLAIM"},
                {"field":"kernel_results","role":"DERIVED_CLAIM"},{"field":"experiment_ordinals","role":"DERIVED_CLAIM"},
                {"field":"causal_ordinals","role":"DERIVED_CLAIM"},{"field":"correspondence_evolution","role":"DERIVED_CLAIM"},
                {"field":"protected_observable_trace","role":"DERIVED_CLAIM"},{"field":"first_protected_mismatch","role":"DERIVED_CLAIM"},
                {"field":"mismatch_observable_id","role":"DERIVED_CLAIM"},{"field":"metadata_note","role":"NONAUTHORITATIVE_METADATA"}
            ]),
        ),
        (
            "CERTIFICATE_AUTHORITY_BINDING_V1.json",
            json!({
                "schema":"G8_CERTIFICATE_AUTHORITY_BINDING_V1","G3_ROOT":G3_ROOT,"G4_ROOT":G4_ROOT,"G5_ROOT":G5_ROOT,"G6_ROOT":G6_ROOT,"G7_ROOT":G7_ROOT,
                "THETA_STAR_ID":THETA_STAR_ID,"CERTIFICATE_SCHEMA_ID":SEPARATOR_SCHEMA_ID,"CERTIFICATE_SCHEMA_VERSION":SEPARATOR_SCHEMA_VERSION,
                "G8_VERIFIER_CONTRACT_HASH":verifier_contract_hash(),"AUTHORITY_BUNDLE_HASH":authority_bundle_hash(),
                "cross_lineage_replay":"AUTHORITY_LINEAGE_MISMATCH_TO_REJECT"
            }),
        ),
        (
            "SEPARATOR_CERTIFICATE_SCHEMA_V1.json",
            json!({
                "schema":SEPARATOR_SCHEMA_ID,"version":SEPARATOR_SCHEMA_VERSION,
                "primitive_evidence":["authority_binding","frozen_comparison","fiber_certificate","neutral_token_sequence"],
                "derived_claims_recomputed":["state_traces","protected_traces","first_mismatch_ordinal","mismatch_observable_id"],
                "epsilon_supported":true
            }),
        ),
        (
            "CANONICAL_WITNESS_RANKING_V1.json",
            json!({
                "schema":"G8_CANONICAL_WITNESS_RANKING_V1","construction":"FINITE_SHELL_DOVETAIL",
                "rank_key":["shell=max(token_length,max_abs_coordinate)","token_length","max_abs_coordinate","sum_abs_coordinates","finite_signed_coordinate_code"],
                "epsilon_first":true,"rank_computable":"PROVEN","every_finite_candidate_has_finite_rank":"PROVEN",
                "enumeration_complete_over_declared_word_space":"PROVEN","enumeration_deterministic":"PROVEN",
                "every_strict_lower_rank_set_finite":"PROVEN","parallel_commit_rule":"RANK_ORDERED",
                "DO_NOT_SEARCH_OVER_LAMBDA":true,"DO_NOT_SEARCH_OVER_M":true
            }),
        ),
        (
            "FAIR_RANKING_PROOF_V1.json",
            json!({
                "schema":"G8_FAIR_RANKING_PROOF_V1","status":"PROVEN",
                "argument":["EVERY_FINITE_WORD_HAS_FINITE_LENGTH_AND_FINITE_INTEGER_COORDINATES","ITS_MAX_LENGTH_MAGNITUDE_SHELL_IS_FINITE","EACH_SHELL_HAS_FINITE_LENGTH_BOUND_FINITE_COORDINATE_BOX_AND_FINITE_COVERAGE_ALPHABET","LEXICOGRAPHIC_ORDER_WITHIN_A_FINITE_SHELL_IS FINITE","ENUMERATING_SHELLS_FROM_ZERO_EVENTUALLY_VISITS_EVERY_WORD"],
                "canonical_first_obligation":"ALL_LOWER_RANKS_DISPOSITIONED_BEFORE_COMMIT"
            }),
        ),
        (
            "FROZEN_COMPARISON_INSTANCE_CONTRACT_V1.json",
            json!({
                "schema":"G8_FROZEN_COMPARISON_INSTANCE_CONTRACT_V1","fixed":["pi_a","pi_b","gamma","ThetaStar","Lambda_ab","M0_ab","C_a","C_b","fiber"],
                "mutable_only":"WITNESS_TOKEN_SEQUENCE","side_realizations_recomputed":true,"M_evolution_recomputed":true,
                "forbidden_mutations":["STARTS","FIBER","CONTEXT","THETA","LAMBDA","INITIAL_M","G4_MATCH","G5_PRESENTABILITY"]
            }),
        ),
        (
            "SHRINK_TERMINATION_PROOF_V1.json",
            json!({
                "schema":"G8_SHRINK_TERMINATION_PROOF_V1","shrinker":"DELETION_ONLY_V1","measure":"TOKEN_LENGTH",
                "argument":"EVERY_ACCEPTED_CHILD_HAS STRICTLY SMALLER NATURAL TOKEN LENGTH","status":"STRICT_COST_DECREASE_UNDER_WELL_FOUNDED_ORDER",
                "every_child_independently_verified":true,"global_minimality":false
            }),
        ),
        (
            "BOUNDED_EXHAUSTION_VERIFIER_V1.json",
            json!({
                "schema":"G8_BOUNDED_EXHAUSTION_VERIFIER_V1","answers":"DECLARED_FINITE_REGION_COMPLETELY_COVERED",
                "checks":["DOMAIN_ID_RECOMPUTED","EXACT_CARDINALITY","EVERY_CANONICAL_INDEX_PRESENT_ONCE","INDEX_RANGE","VISITED_ACCUMULATOR_HASH"],
                "candidate_counter_sufficient":false,"separate_from_separator_verifier":true
            }),
        ),
        (
            "FINITE_DOMAIN_INDEXING_CONTRACT_V1.json",
            json!({
                "schema":"G8_FINITE_DOMAIN_INDEXING_CONTRACT_V1","domain":"ALL_SOURCE_VALID_WORDS_WITH_RANK_SHELL_AT_MOST_BOUND",
                "order":"CANONICAL_WITNESS_RANKING_V1","indices":"DENSE_ZERO_BASED","domain_id":"SHA256_CANONICAL_SERIALIZATION",
                "finite":"PROVEN_FROM_FINITE_SHELL"
            }),
        ),
        (
            "FINITE_DOMAIN_COVERAGE_RECEIPT_SCHEMA_V1.json",
            json!({
                "schema":"G8_FINITE_DOMAIN_COVERAGE_RECEIPT_V1","required":["domain_id","domain_cardinality","visited_indices","visited_accumulator_hash","accepted_separator_indices"],
                "verified_coverage":"Visited equals exact canonical domain index set","counter_only":false
            }),
        ),
        (
            "UNIVERSAL_PROOF_SYSTEM_V1.json",
            json!({
                "schema":"G8_UNIVERSAL_PROOF_SYSTEM_V1","proof_system_id":UNIVERSAL_PROOF_SYSTEM_ID,
                "scope":"FINITE_DETERMINISTIC_TOTAL_TRANSITION_SYSTEMS_WITH_FINITE_SHARED_ALPHABET",
                "proof_object":"RELATION_ON_PRODUCT_STATES","axioms":["INITIAL_PAIR_IN_RELATION","OUTPUTS_MATCH"],
                "inference_rule":"RELATION_CLOSED_UNDER_EVERY_ALPHABET_SYMBOL","proof_kernel":"SMALL_DETERMINISTIC_RELATION_CHECKER",
                "solver_unsat_is_proof":false,"04A_applicability":"NOT_EARNED"
            }),
        ),
        (
            "UNIVERSAL_PROOF_SYSTEM_SOUNDNESS_ARGUMENT_V1.json",
            json!({
                "schema":"G8_UNIVERSAL_PROOF_SYSTEM_SOUNDNESS_ARGUMENT_V1","status":"PROVEN_FOR_DECLARED_FINITE_SYSTEM_SCOPE",
                "base":"EMPTY_WORD_ENDS_AT_INITIAL_RELATED_PAIR_AND_OUTPUTS_MATCH",
                "step":"IF_PREFIX_ENDPOINT_PAIR_IS_RELATED_CLOSURE_PLACES_EACH_ONE_SYMBOL_SUCCESSOR_IN_RELATION_AND_OUTPUTS_MATCH",
                "conclusion":"ALL_FINITE_WORDS_HAVE_MATCHING_PROTECTED_OUTPUTS","completeness":"NOT_REQUIRED_OR_CLAIMED_FOR_ARBITRARY_INPUT_PROOFS"
            }),
        ),
        (
            "REFERENCE_ORACLE_PROVENANCE_V1.json",
            json!({
                "schema":"G8_REFERENCE_ORACLE_PROVENANCE_V1","ground_truth_construction_method":"DECLARATIVE_FINITE_PRODUCT_BFS_AND_HAND_ALGEBRAIC_FIXTURES",
                "oracle_implementation_id":"INDEPENDENT_FINITE_PRODUCT_ORACLE_V1","oracle_authority_source":"FINITE_EXHAUSTIVE_STATE_PRODUCT",
                "production_verifier_dependency":"NONE","production_verifier_as_expected_answer":false
            }),
        ),
        (
            "EPSILON_SEPARATOR_CONTRACT_V1.json",
            json!({
                "schema":"G8_EPSILON_SEPARATOR_CONTRACT_V1","neutral_token_sequence":[],"token_length":0,
                "first_protected_mismatch":"INITIAL_G4_PROJECTION","presentation_receipt":"ABSENT_BY_DEFINITION","ranking":"FIRST"
            }),
        ),
        (
            "VERIFIER_IMPLEMENTATION_DIVERGENCE_POLICY_V1.json",
            json!({
                "schema":"G8_VERIFIER_IMPLEMENTATION_DIVERGENCE_POLICY_V1",
                "default":{"classification":"VERIFIER_IMPLEMENTATION_DIVERGENCE","disposition":["HALT","REPAIR","REQUALIFY"]},
                "predecessor_rebase_requires":"INDEPENDENTLY_DEMONSTRATED_PREDECESSOR_SEMANTIC_CONTRADICTION"
            }),
        ),
        (
            "WITNESS_VS_OBSERVER_MINIMIZATION_BOUNDARY_V1.json",
            json!({
                "schema":"G8_WITNESS_VS_OBSERVER_MINIMIZATION_BOUNDARY_V1","authorized":["WITNESS_SHRINKING","FINITE_BOX_WITNESS_MINIMALITY"],
                "not_authorized":["NO_OBSERVER_QUOTIENT_CLAIM","NO_STATE_MINIMIZATION_CLAIM","NO_MEMORY_MINIMIZATION_CLAIM","NO_FIELD_REMOVABILITY_CLAIM"]
            }),
        ),
        (
            "TRUSTED_SEPARATOR_PATH_V1.json",
            json!({
                "schema":"G8_TRUSTED_SEPARATOR_PATH_V1","path":["QUALIFIED_STARTS","QUALIFIED_G6_FIBER_CERTIFICATE","FROZEN_COMPARISON_INSTANCE","CANDIDATE_GENERATION","AUTHORITY_BOUND_CERTIFICATE","INDEPENDENT_SEMANTIC_RECOMPUTATION","EXACT_VERIFIER_ACCEPT","G7_AUTHORIZED_VERDICT"],
                "pre_verifier_truth":false
            }),
        ),
        (
            "PREDECESSOR_RESTRICTION_INHERITANCE_V1.json",
            json!({
                "schema":"G8_PREDECESSOR_RESTRICTION_INHERITANCE_V1","G3":"MIXED_REACHABILITY_AUTHORITY","G4":"GRAMMAR_STATE_EVENT_NOT_EVALUABLE",
                "G5":"SOUND_CONTINUATION_ENVELOPE","G7":"INCOMPLETE_DECISION_AUTHORITY","restrictions_removed":false,
                "successful_result":"WITNESS_LABORATORY_QUALIFIED_WITH_RESTRICTIONS"
            }),
        ),
        (
            "G8_NONCLAIMS_V1.json",
            json!({
                "schema":"G8_NONCLAIMS_V1","real_04A_pair_result":false,"04A_fiber_decider":false,"04A_equivalence_decider":false,
                "global_witness_minimality":false,"no_witness_means_equivalent":false,"observer_quotient":false,"state_minimality":false,
                "memory_minimality":false,"field_removability":false,"prediction":false,"economic":false,"trading":false
            }),
        ),
    ]
}
